/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.FlowLayout;

/**
 *
 * @author Buwaneka
 */
public class Add_Members extends javax.swing.JPanel {

    /**
     * Creates new form Add_Members
     */
    public Add_Members() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2_Sub_members_set = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFocusable(false);
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home_Pages/Icon_Add_Members.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 10, 60, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 19)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText(" Members");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 10, 160, 40);

        jPanel2_Sub_members_set.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2_Sub_members_set.setLayout(null);
        jPanel1.add(jPanel2_Sub_members_set);
        jPanel2_Sub_members_set.setBounds(0, 70, 1040, 530);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(20, 60, 1010, 20);

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jButton1.setText("Add Members");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 192, 29)));
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(320, 20, 150, 30);

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jButton2.setText("Member Payments");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 192, 29)));
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(500, 20, 170, 30);

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jButton3.setText("View Member Payments");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 192, 29)));
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(690, 20, 200, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        jPanel2_Sub_members_set.removeAll();
        jPanel2_Sub_members_set.setLayout(new FlowLayout());
        Admin.add_members.Add_members m = new Admin.add_members.Add_members();
        m.setVisible(true);
        jPanel2_Sub_members_set.add(m);
        jPanel2_Sub_members_set.updateUI();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        jPanel2_Sub_members_set.removeAll();
        jPanel2_Sub_members_set.setLayout(new FlowLayout());
        Admin.add_members.Members_Payments m = new Admin.add_members.Members_Payments();
        m.setVisible(true);
        jPanel2_Sub_members_set.add(m);
        jPanel2_Sub_members_set.updateUI();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            jPanel2_Sub_members_set.removeAll();
            jPanel2_Sub_members_set.setLayout(new FlowLayout());
            Admin.add_members.Veiw_Pament_Histry vp = new Admin.add_members.Veiw_Pament_Histry();
            vp.setVisible(true);
            jPanel2_Sub_members_set.add(vp);
            jPanel2_Sub_members_set.updateUI();
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2_Sub_members_set;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables


}
