/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin.User_acc;

import Class_Files.DB;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Buwaneka
 */
public class User_acc extends javax.swing.JPanel {

    int Eid;

    /**
     * Creates new form User_acc
     */
    public User_acc() {
        initComponents();
        jScrollPane1.setVisible(false);
        jList1.setVisible(false);
        jButton3.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1_Account_Type = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        txtReEnter_Pass = new javax.swing.JPasswordField();
        txtanswer = new javax.swing.JTextField();
        jComboBox2_Security_Q = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Name :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(80, 100, 120, 21);

        jList1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jList1MousePressed(evt);
            }
        });
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jList1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(200, 128, 240, 60);

        txtName.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
        });
        jPanel1.add(txtName);
        txtName.setBounds(200, 100, 240, 28);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText(" Email :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 140, 120, 21);

        txtEmail.setEditable(false);
        txtEmail.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        jPanel1.add(txtEmail);
        txtEmail.setBounds(200, 140, 240, 28);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Account Type :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 180, 120, 21);

        jComboBox1_Account_Type.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jComboBox1_Account_Type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Admin", "Super Admin" }));
        jComboBox1_Account_Type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_Account_TypeActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1_Account_Type);
        jComboBox1_Account_Type.setBounds(200, 180, 240, 30);

        jLabel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 0, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(50, 60, 470, 200);

        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Security Question :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(570, 130, 120, 21);

        jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Answer :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(570, 170, 150, 21);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("User Name :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(80, 310, 120, 21);

        txtUserName.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserNameKeyReleased(evt);
            }
        });
        jPanel1.add(txtUserName);
        txtUserName.setBounds(190, 310, 240, 28);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Password :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 350, 120, 30);

        txtPass.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPassKeyReleased(evt);
            }
        });
        jPanel1.add(txtPass);
        txtPass.setBounds(190, 350, 240, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Re enter :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(80, 390, 120, 30);

        txtReEnter_Pass.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txtReEnter_Pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtReEnter_PassKeyReleased(evt);
            }
        });
        jPanel1.add(txtReEnter_Pass);
        txtReEnter_Pass.setBounds(190, 390, 240, 30);

        txtanswer.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txtanswer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtanswerKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtanswerKeyTyped(evt);
            }
        });
        jPanel1.add(txtanswer);
        txtanswer.setBounds(700, 170, 240, 28);

        jComboBox2_Security_Q.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jComboBox2_Security_Q.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "What is your favourite color?", "What is your favourite drink?", "What is your favourite Food?", "What is your Blood type?", "What is your favourite place to visit?" }));
        jComboBox2_Security_Q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2_Security_QActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2_Security_Q);
        jComboBox2_Security_Q.setBounds(700, 130, 240, 30);

        jButton3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jButton3.setText("Create ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(810, 410, 160, 40);

        jLabel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Recovery Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 0, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(540, 60, 470, 210);

        jLabel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Security Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 0, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(50, 270, 470, 200);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased

        try {

            if (!txtName.getText().trim().equals("")) {
                ResultSet rs = Class_Files.DB.search("SELECT * FROM employee_reg WHERE First_Name LIKE '" + txtName.getText() + "%' || Last_Name LIKE '" + txtName.getText() + "%' ");
                Vector v = new Vector();
                jList1.removeAll();

                while (rs.next()) {

                    String sts = rs.getString("Status");

                    if (sts.equals("On")) {

                        jScrollPane1.setVisible(true);
                        jList1.setVisible(true);

                        String Fn = rs.getString("First_Name");
                        String Ln = rs.getString("Last_Name");
                        v.add(Fn + " " + Ln);
                        jList1.setListData(v);

                    }

                }

            } else {
                jScrollPane1.setVisible(false);
                jList1.setVisible(false);

            }

            ///////////Validation/////////////////////////////////
            if (txtName.getText().length() == 0) {
                jButton3.setEnabled(false);
            } else {

                if (txtName.getText().length() != 0
                        && txtEmail.getText().length() != 0
                        && jComboBox1_Account_Type.getSelectedIndex() != 0
                        && txtUserName.getText().length() != 0
                        && txtPass.getText().length() != 0
                        && txtReEnter_Pass.getText().length() != 0
                        && txtPass.getText().equals(txtReEnter_Pass.getText())
                        && jComboBox2_Security_Q.getSelectedIndex() != 0
                        && txtanswer.getText().length() != 0) {

                    jButton3.setEnabled(true);
                } else {
                    jButton3.setEnabled(false);
                }
            }

            /////////////////////////////////////////////////////////
            if (jList1.isVisible()) {
                if (evt.getKeyCode() == 40) {
                    jList1.grabFocus();
                }
            }

            if (evt.getKeyCode() == 10) {
                load_email();
                jComboBox1_Account_Type.grabFocus();

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtNameKeyReleased

    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped

        try {
            System.gc();

            char c = evt.getKeyChar();
            if (Character.isDigit(c) || c == 32) {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtNameKeyTyped

    private void txtanswerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtanswerKeyTyped

        try {
            System.gc();

            char c = evt.getKeyChar();
            if (Character.isDigit(c) || c == 32) {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtanswerKeyTyped

    private void jList1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyReleased

        try {
            System.gc();
            if (evt.getKeyCode() == 10) {
                txtName.setText(jList1.getSelectedValue().toString());
                jScrollPane1.setVisible(false);
                jList1.setVisible(false);
                load_email();

            }
        } catch (NullPointerException e) {
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jList1KeyReleased

    private void jList1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MousePressed

        try {
            System.gc();
            if (evt.getClickCount() == 2) {

                txtName.setText(jList1.getSelectedValue().toString());
                load_email();
                jScrollPane1.setVisible(false);
                jList1.setVisible(false);

            }

        } catch (NullPointerException n) {
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jList1MousePressed

    private void txtReEnter_PassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReEnter_PassKeyReleased

        try {

            String pass = txtPass.getText();

            if (pass.equals(txtReEnter_Pass.getText())) {
                txtReEnter_Pass.setForeground(Color.GREEN);
            } else {
                txtReEnter_Pass.setForeground(Color.red);
            }

            ///////////Validation/////////////////////////////////
            if (txtReEnter_Pass.getText().length() == 0) {
                jButton3.setEnabled(false);
            } else {

                if (txtName.getText().length() != 0
                        && txtEmail.getText().length() != 0
                        && jComboBox1_Account_Type.getSelectedIndex() != 0
                        && txtUserName.getText().length() != 0
                        && txtPass.getText().length() != 0
                        && txtReEnter_Pass.getText().length() != 0
                        && txtPass.getText().equals(txtReEnter_Pass.getText())
                        && jComboBox2_Security_Q.getSelectedIndex() != 0
                        && txtanswer.getText().length() != 0) {

                    jButton3.setEnabled(true);
                } else {
                    jButton3.setEnabled(false);
                }
            }
            
            if (evt.getKeyCode() == 10) {
                jComboBox2_Security_Q.grabFocus();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtReEnter_PassKeyReleased

    private void txtPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyReleased

        try {

            String pass = txtPass.getText();

            if (pass.equals(txtReEnter_Pass.getText())) {
                txtReEnter_Pass.setForeground(Color.GREEN);
            } else {
                txtReEnter_Pass.setForeground(Color.red);
            }

            ///////////Validation/////////////////////////////////
            if (txtPass.getText().length() == 0) {
                jButton3.setEnabled(false);
            } else {

                if (txtName.getText().length() != 0
                        && txtEmail.getText().length() != 0
                        && jComboBox1_Account_Type.getSelectedIndex() != 0
                        && txtUserName.getText().length() != 0
                        && txtPass.getText().length() != 0
                        && txtReEnter_Pass.getText().length() != 0
                        && txtPass.getText().equals(txtReEnter_Pass.getText())
                        && jComboBox2_Security_Q.getSelectedIndex() != 0
                        && txtanswer.getText().length() != 0) {

                    jButton3.setEnabled(true);
                } else {
                    jButton3.setEnabled(false);
                }
            }
            
            if (evt.getKeyCode() == 10) {
                txtReEnter_Pass.grabFocus();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtPassKeyReleased

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        try {

            ///////////Validation/////////////////////////////////
            if (txtEmail.getText().length() == 0) {
                jButton3.setEnabled(false);
            } else {

                if (txtName.getText().length() != 0
                        && txtEmail.getText().length() != 0
                        && jComboBox1_Account_Type.getSelectedIndex() != 0
                        && txtUserName.getText().length() != 0
                        && txtPass.getText().length() != 0
                        && txtReEnter_Pass.getText().length() != 0
                        && txtPass.getText().equals(txtReEnter_Pass.getText())
                        && jComboBox2_Security_Q.getSelectedIndex() != 0
                        && txtanswer.getText().length() != 0) {

                    jButton3.setEnabled(true);
                } else {
                    jButton3.setEnabled(false);
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_txtEmailKeyReleased

    private void jComboBox1_Account_TypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_Account_TypeActionPerformed

        try {

            ///////////Validation/////////////////////////////////
            if (jComboBox1_Account_Type.getSelectedIndex() == 0) {
                jButton3.setEnabled(false);
            } else {

                if (txtName.getText().length() != 0
                        && txtEmail.getText().length() != 0
                        && jComboBox1_Account_Type.getSelectedIndex() != 0
                        && txtUserName.getText().length() != 0
                        && txtPass.getText().length() != 0
                        && txtReEnter_Pass.getText().length() != 0
                        && txtPass.getText().equals(txtReEnter_Pass.getText())
                        && jComboBox2_Security_Q.getSelectedIndex() != 0
                        && txtanswer.getText().length() != 0) {

                    jButton3.setEnabled(true);
                } else {
                    jButton3.setEnabled(false);
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jComboBox1_Account_TypeActionPerformed

    private void txtUserNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyReleased

        try {

            ///////////Validation/////////////////////////////////
            if (txtUserName.getText().length() == 0) {
                jButton3.setEnabled(false);
            } else {

                if (txtName.getText().length() != 0
                        && txtEmail.getText().length() != 0
                        && jComboBox1_Account_Type.getSelectedIndex() != 0
                        && txtUserName.getText().length() != 0
                        && txtPass.getText().length() != 0
                        && txtReEnter_Pass.getText().length() != 0
                        && txtPass.getText().equals(txtReEnter_Pass.getText())
                        && jComboBox2_Security_Q.getSelectedIndex() != 0
                        && txtanswer.getText().length() != 0) {

                    jButton3.setEnabled(true);
                } else {
                    jButton3.setEnabled(false);
                }
            }
            
            if (evt.getKeyCode() == 10) {
                txtPass.grabFocus();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtUserNameKeyReleased

    private void jComboBox2_Security_QActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2_Security_QActionPerformed

        try {

            ///////////Validation/////////////////////////////////
            if (jComboBox2_Security_Q.getSelectedIndex() == 0) {
                jButton3.setEnabled(false);
            } else {

                if (txtName.getText().length() != 0
                        && txtEmail.getText().length() != 0
                        && jComboBox1_Account_Type.getSelectedIndex() != 0
                        && txtUserName.getText().length() != 0
                        && txtPass.getText().length() != 0
                        && txtReEnter_Pass.getText().length() != 0
                        && txtPass.getText().equals(txtReEnter_Pass.getText())
                        && jComboBox2_Security_Q.getSelectedIndex() != 0
                        && txtanswer.getText().length() != 0) {

                    jButton3.setEnabled(true);
                } else {
                    jButton3.setEnabled(false);
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jComboBox2_Security_QActionPerformed

    private void txtanswerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtanswerKeyReleased

        try {

            ///////////Validation/////////////////////////////////
            if (txtEmail.getText().length() == 0) {
                jButton3.setEnabled(false);
            } else {

                if (txtName.getText().length() != 0
                        && txtEmail.getText().length() != 0
                        && jComboBox1_Account_Type.getSelectedIndex() != 0
                        && txtUserName.getText().length() != 0
                        && txtPass.getText().length() != 0
                        && txtReEnter_Pass.getText().length() != 0
                        && txtPass.getText().equals(txtReEnter_Pass.getText())
                        && jComboBox2_Security_Q.getSelectedIndex() != 0
                        && txtanswer.getText().length() != 0) {

                    jButton3.setEnabled(true);
                } else {
                    jButton3.setEnabled(false);
                }
            }

             
            if (evt.getKeyCode() == 10) {
                jButton3.grabFocus();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtanswerKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try {
            byte a = 0;
            String Name[] = txtName.getText().split(" ");
            ResultSet rs = DB.search("SELECT * FROM employee_reg WHERE First_Name = '" + Name[0] + "' &&  Last_Name='" + Name[1] + "' ");
            while (rs.next()) {
                a = 1;
                Eid = rs.getInt("E_id");
            }

            if (a == 0) {

                JOptionPane.showMessageDialog(this, "Cheak Your name..!");

            } else {

                byte b = 0;
                ResultSet rss = DB.search("SELECT User_Name FROM user_account WHERE User_Name = '" + txtUserName.getText() + "' ");
                while (rss.next()) {
                    b = 1;
                }

                if (b == 1) {
                    JOptionPane.showMessageDialog(this, "Sorry this " + txtUserName.getText() + " user name already available.");
                } else {

                    int c = 0;

                    ////////////////////cheak alredy accunt avilabe?
                    ResultSet rs3 = DB.search("SELECT * FROM user_account WHERE Name = '" + txtName.getText() + "'  ");
                    while (rs3.next()) {
                        c = 1;
                    }

                    if (c == 1) {
                        JOptionPane.showMessageDialog(this, "This " + txtName.getText() + " User Aready have Account..! ");
                    } else {

                        DB.sud("INSERT INTO user_account(E_Id,Name,Email,Act_type,User_Name,Password,Sec_q,Answer,Status)VALUES('" + Eid + "'"
                                + ",'" + txtName.getText() + "' "
                                + ", '" + txtEmail.getText() + "' "
                                + ", '" + jComboBox1_Account_Type.getSelectedItem() + "'"
                                + ", '" + txtUserName.getText() + "' "
                                + ", '" + txtPass.getText() + "'"
                                + ", '" + jComboBox2_Security_Q.getSelectedItem() + "' "
                                + ", '" + txtanswer.getText() + "'"
                                + ", '" + "Active" + "' )");

                        JOptionPane.showMessageDialog(this, "Account Created successfully  .!!");
                        emtyTf();

                    }

                }

            }

        } catch (ArrayIndexOutOfBoundsException a) {
            JOptionPane.showMessageDialog(this, "Please Cheack Your name..!");
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1_Account_Type;
    private javax.swing.JComboBox jComboBox2_Security_Q;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtReEnter_Pass;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtanswer;
    // End of variables declaration//GEN-END:variables

    private void load_email() {
        try {

            if (!txtName.getText().equals("")) {

                byte d = 0;

                String Name[] = txtName.getText().split(" ");
                Vector v = new Vector();
                ResultSet rs = Class_Files.DB.search("SELECT * FROM employee_reg WHERE First_Name = '" + Name[0] + "' && Last_Name='" + Name[1] + "' ");
                while (rs.next()) {
                    d = 1;
                    txtEmail.setText(rs.getString("Email"));
                }

                if (d == 0) {
                    JOptionPane.showMessageDialog(this, "No Result available cheack Your name..!");
                }

            }

        } catch (ArrayIndexOutOfBoundsException a) {
            JOptionPane.showMessageDialog(this, "No Result available cheack Your name..!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void emtyTf() {
        txtName.setText("");
        txtEmail.setText("");
        jComboBox1_Account_Type.setSelectedIndex(0);
        txtUserName.setText("");
        txtPass.setText("");
        jComboBox2_Security_Q.setSelectedIndex(0);
        txtanswer.setText("");
        txtReEnter_Pass.setText("");
    }
}
