/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin.User_acc;

import Class_Files.DB;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Buwaneka
 */
public class Veiw_acc extends javax.swing.JPanel {

    /**
     * Creates new form Veiw_acc
     */
    public Veiw_acc() {
        initComponents();
        jScrollPane1.setVisible(false);
        jList1.setVisible(false);
        jButton1_serach1.setEnabled(false);

        jCheckBox2.setSelected(true);
        jButton2_Update.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        txtName = new javax.swing.JTextField();
        jButton2_Update = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1_Account_Type = new javax.swing.JComboBox();
        txtUserName_set = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2_Security_Q = new javax.swing.JComboBox();
        txtPass_set = new javax.swing.JPasswordField();
        txtEm_Set = new javax.swing.JTextField();
        txtanswer_set = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName_Set1 = new javax.swing.JTextField();
        jButton1_serach1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton2_veiw_All = new javax.swing.JButton();
        jButton2_C_All = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jList1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jList1MousePressed(evt);
            }
        });
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jList1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(170, 78, 240, 60);

        txtName.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
        });
        jPanel1.add(txtName);
        txtName.setBounds(170, 50, 240, 28);

        jButton2_Update.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jButton2_Update.setText("Update");
        jButton2_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2_Update);
        jButton2_Update.setBounds(840, 440, 170, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Email", "Account Type", "User Name", "Password", "Security Question", "Answer", "Status"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 180, 990, 120);

        jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Name :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(50, 50, 120, 21);

        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Name :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 330, 140, 21);

        jComboBox1_Account_Type.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jComboBox1_Account_Type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Admin", "Super Admin" }));
        jComboBox1_Account_Type.setFocusable(false);
        jComboBox1_Account_Type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_Account_TypeActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1_Account_Type);
        jComboBox1_Account_Type.setBounds(130, 410, 240, 30);

        txtUserName_set.setEditable(false);
        txtUserName_set.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txtUserName_set.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserName_setKeyReleased(evt);
            }
        });
        jPanel1.add(txtUserName_set);
        txtUserName_set.setBounds(520, 330, 240, 28);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText(" Email :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 370, 140, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Account Type :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 401, 120, 40);

        jComboBox2_Security_Q.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jComboBox2_Security_Q.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "What is your favourite color?", "What is your favourite drink?", "What is your favourite Food?", "What is your Blood type?", "What is your favourite place to visit?" }));
        jComboBox2_Security_Q.setEnabled(false);
        jComboBox2_Security_Q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2_Security_QActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2_Security_Q);
        jComboBox2_Security_Q.setBounds(520, 410, 240, 30);

        txtPass_set.setEditable(false);
        txtPass_set.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txtPass_set.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPass_setKeyReleased(evt);
            }
        });
        jPanel1.add(txtPass_set);
        txtPass_set.setBounds(520, 370, 240, 30);

        txtEm_Set.setEditable(false);
        txtEm_Set.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txtEm_Set.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEm_SetKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEm_SetKeyTyped(evt);
            }
        });
        jPanel1.add(txtEm_Set);
        txtEm_Set.setBounds(130, 370, 240, 28);

        txtanswer_set.setEditable(false);
        txtanswer_set.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txtanswer_set.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtanswer_setKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtanswer_setKeyTyped(evt);
            }
        });
        jPanel1.add(txtanswer_set);
        txtanswer_set.setBounds(520, 450, 240, 28);

        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Security Question :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(390, 400, 120, 40);

        jLabel13.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Answer :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(390, 450, 150, 21);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("User Name :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(390, 330, 120, 21);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Password :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(390, 360, 120, 40);

        txtName_Set1.setEditable(false);
        txtName_Set1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txtName_Set1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtName_Set1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtName_Set1KeyTyped(evt);
            }
        });
        jPanel1.add(txtName_Set1);
        txtName_Set1.setBounds(130, 330, 240, 28);

        jButton1_serach1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jButton1_serach1.setText("Search");
        jButton1_serach1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_serach1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1_serach1);
        jButton1_serach1.setBounds(320, 100, 130, 30);

        jLabel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 0, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(30, 10, 470, 150);

        buttonGroup1.add(jCheckBox1);
        jCheckBox1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jCheckBox1.setText("Active");
        jCheckBox1.setContentAreaFilled(false);
        jCheckBox1.setFocusPainted(false);
        jCheckBox1.setFocusable(false);
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(810, 340, 61, 28);

        buttonGroup1.add(jCheckBox2);
        jCheckBox2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jCheckBox2.setText("Deactive");
        jCheckBox2.setContentAreaFilled(false);
        jCheckBox2.setFocusable(false);
        jPanel1.add(jCheckBox2);
        jCheckBox2.setBounds(901, 340, 90, 29);

        jButton2_veiw_All.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jButton2_veiw_All.setText("Veiw All");
        jButton2_veiw_All.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_veiw_AllActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2_veiw_All);
        jButton2_veiw_All.setBounds(720, 140, 130, 30);

        jButton2_C_All.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jButton2_C_All.setText("Clear All");
        jButton2_C_All.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_C_AllActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2_C_All);
        jButton2_C_All.setBounds(860, 140, 130, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased

        try {

            if (!txtName.getText().trim().equals("")) {
                ResultSet rs = Class_Files.DB.search("SELECT * FROM employee_reg WHERE First_Name LIKE '" + txtName.getText() + "%' || Last_Name LIKE '" + txtName.getText() + "%' ");
                Vector v = new Vector();
                jList1.removeAll();

                while (rs.next()) {

                    String sts = rs.getString("Status");

                    if (sts.equals("On")) {

                        jScrollPane1.setVisible(true);
                        jList1.setVisible(true);

                        String Fn = rs.getString("First_Name");
                        String Ln = rs.getString("Last_Name");
                        v.add(Fn + " " + Ln);
                        jList1.setListData(v);

                    }

                }

            } else {
                jScrollPane1.setVisible(false);
                jList1.setVisible(false);

            }

            //validation
            if (txtName.getText().length() == 0) {
                jButton1_serach1.setEnabled(false);
            } else {
                if (txtName.getText().length() != 0) {

                    jButton1_serach1.setEnabled(true);
                }
            }

            if (jList1.isVisible()) {
                if (evt.getKeyCode() == 40) {
                    jList1.grabFocus();
                }
            }

            if (evt.getKeyCode() == 10) {
                jButton1_serach1.grabFocus();
            }

            ///////////Validation/////////////////////////////////
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped

        try {
            System.gc();

            char c = evt.getKeyChar();
            if (Character.isDigit(c) || c == 32) {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtNameKeyTyped

    private void jList1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MousePressed

        try {
            System.gc();
            if (evt.getClickCount() == 2) {

                txtName.setText(jList1.getSelectedValue().toString());

                jScrollPane1.setVisible(false);
                jList1.setVisible(false);

                jButton1_serach1.grabFocus();

            }

        } catch (NullPointerException n) {
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jList1MousePressed

    private void jList1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyReleased

        try {
            System.gc();
            if (evt.getKeyCode() == 10) {
                txtName.setText(jList1.getSelectedValue().toString());
                jScrollPane1.setVisible(false);
                jList1.setVisible(false);
                jButton1_serach1.grabFocus();

            }
        } catch (NullPointerException e) {
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jList1KeyReleased

    private void jComboBox1_Account_TypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_Account_TypeActionPerformed

        try {

            ///////////Validation/////////////////////////////////
            if (jComboBox1_Account_Type.getSelectedIndex() == 0) {

                jButton2_Update.setEnabled(false);
            } else {

                if (jComboBox1_Account_Type.getSelectedIndex() != 0) {

                    jButton2_Update.setEnabled(true);
                } else {
                    jButton2_Update.setEnabled(false);
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jComboBox1_Account_TypeActionPerformed

    private void txtUserName_setKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserName_setKeyReleased


    }//GEN-LAST:event_txtUserName_setKeyReleased

    private void jComboBox2_Security_QActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2_Security_QActionPerformed

    }//GEN-LAST:event_jComboBox2_Security_QActionPerformed

    private void txtPass_setKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPass_setKeyReleased

    }//GEN-LAST:event_txtPass_setKeyReleased

    private void txtEm_SetKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEm_SetKeyReleased


    }//GEN-LAST:event_txtEm_SetKeyReleased

    private void txtEm_SetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEm_SetKeyTyped

        try {
            System.gc();

            char c = evt.getKeyChar();
            if (Character.isDigit(c) || c == 32) {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtEm_SetKeyTyped

    private void txtanswer_setKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtanswer_setKeyReleased


    }//GEN-LAST:event_txtanswer_setKeyReleased

    private void txtanswer_setKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtanswer_setKeyTyped

        try {
            System.gc();

            char c = evt.getKeyChar();
            if (Character.isDigit(c) || c == 32) {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtanswer_setKeyTyped

    private void txtName_Set1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtName_Set1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName_Set1KeyReleased

    private void txtName_Set1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtName_Set1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName_Set1KeyTyped

    private void jButton1_serach1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_serach1ActionPerformed

        try {
            int a = 0;
            String Name[] = txtName.getText().split(" ");
            ResultSet rs = DB.search("SELECT * FROM user_account WHERE Name = '" + txtName.getText() + "'  ");
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            Vector v = new Vector();
            while (rs.next()) {
                a = 1;

                v.add(rs.getString("Name"));
                v.add(rs.getString("Email"));
                v.add(rs.getString("Act_type"));
                v.add(rs.getString("User_Name"));
                v.add(rs.getString("Password"));
                v.add(rs.getString("Sec_q"));
                v.add(rs.getString("Answer"));
                v.add(rs.getString("Status"));

                dtm.addRow(v);

            }

            if (a == 0) {
                JOptionPane.showMessageDialog(this, "Sorry this user haven't user account..!");
            }

            txtName.setText("");
            jButton1_serach1.setEnabled(false);

        } catch (ArrayIndexOutOfBoundsException a) {
            JOptionPane.showMessageDialog(this, "Please cheak Your name..!");
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton1_serach1ActionPerformed

    private void jButton2_veiw_AllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_veiw_AllActionPerformed

        try {

            ResultSet rs = DB.search("SELECT * FROM user_account ");
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);

            while (rs.next()) {
                Vector v = new Vector();

                v.add(rs.getString("Name"));
                v.add(rs.getString("Email"));
                v.add(rs.getString("Act_type"));
                v.add(rs.getString("User_Name"));
                v.add(rs.getString("Password"));
                v.add(rs.getString("Sec_q"));
                v.add(rs.getString("Answer"));
                v.add(rs.getString("Status"));

                dtm.addRow(v);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton2_veiw_AllActionPerformed
    String Name;
    private void jButton2_C_AllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_C_AllActionPerformed

        try {
            txtName.setText("");
            txtName_Set1.setText("");
            txtEm_Set.setText("");
            jComboBox1_Account_Type.setSelectedIndex(0);
            txtUserName_set.setText("");
            txtPass_set.setText("");
            jComboBox2_Security_Q.setSelectedIndex(0);
            txtanswer_set.setText("");
            jCheckBox2.setSelected(true);
            jButton2_Update.setEnabled(false);

            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton2_C_AllActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed

        try {
            System.gc();

            int row = jTable1.getSelectedRow();

            Name = jTable1.getValueAt(row, 0).toString();
            String Email = jTable1.getValueAt(row, 1).toString();
            String Actype = jTable1.getValueAt(row, 2).toString();
            String Un = jTable1.getValueAt(row, 3).toString();
            String pass = jTable1.getValueAt(row, 4).toString();
            String Secq = jTable1.getValueAt(row, 5).toString();
            String answer = jTable1.getValueAt(row, 6).toString();
            String stats = jTable1.getValueAt(row, 7).toString();

            txtName_Set1.setText(Name);
            txtEm_Set.setText(Email);
            jComboBox1_Account_Type.setSelectedItem(Actype);
            txtUserName_set.setText(Un);
            txtPass_set.setText(pass);
            jComboBox2_Security_Q.setSelectedItem(Secq);
            txtanswer_set.setText(answer);

            if (stats.equals("Active")) {
                jCheckBox1.setSelected(true);
            } else {
                jCheckBox2.setSelected(true);
            }

            jButton2_Update.setEnabled(true);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jTable1MousePressed
    int Ua_id;
    String Status;
    private void jButton2_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_UpdateActionPerformed

        try {

            int a = JOptionPane.showConfirmDialog(this, "Are you sure you want to change account details?", "", JOptionPane.YES_NO_OPTION);

            if (a == 0) {

                //load User Ac_id
                ResultSet rs = DB.search("SELECT Acount_Id FROM user_account WHERE Name = '" + Name + "' ");
                while (rs.next()) {
                    Ua_id = rs.getInt("Acount_Id");
                }

                //Update
                Status = "";

                if (jCheckBox1.isSelected()) {
                    Status = "Active";
                } else {
                    Status = "Deactive";
                }

                DB.sud("UPDATE user_account SET Act_type = '" + jComboBox1_Account_Type.getSelectedItem() + "' "
                        + ", Status = '" + Status + "' WHERE Acount_Id= '" + Ua_id + "' ");

                JOptionPane.showMessageDialog(this, "User Account changed..!");

                tableAdd();

                txtName.setText("");
                txtName_Set1.setText("");
                txtEm_Set.setText("");
                jComboBox1_Account_Type.setSelectedIndex(0);
                txtUserName_set.setText("");
                txtPass_set.setText("");
                jComboBox2_Security_Q.setSelectedIndex(0);
                txtanswer_set.setText("");
                jCheckBox2.setSelected(true);
                jButton2_Update.setEnabled(false);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton2_UpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1_serach1;
    private javax.swing.JButton jButton2_C_All;
    private javax.swing.JButton jButton2_Update;
    private javax.swing.JButton jButton2_veiw_All;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox jComboBox1_Account_Type;
    private javax.swing.JComboBox jComboBox2_Security_Q;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtEm_Set;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName_Set1;
    private javax.swing.JPasswordField txtPass_set;
    private javax.swing.JTextField txtUserName_set;
    private javax.swing.JTextField txtanswer_set;
    // End of variables declaration//GEN-END:variables

    private void tableAdd() {

        try {

            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            Vector v = new Vector();
            v.add(txtName_Set1.getText());
            v.add(txtEm_Set.getText());
            v.add(jComboBox1_Account_Type.getSelectedItem());
            v.add(txtUserName_set.getText());
            v.add(txtPass_set.getText());
            v.add(jComboBox2_Security_Q.getSelectedItem());
            v.add(txtanswer_set.getText());
            v.add(Status);

            dtm.addRow(v);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }
}
