/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin.add_members;

import Class_Files.DB;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.channels.FileChannel;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Buwaneka
 */
public class Add_members extends javax.swing.JPanel {

    Image img;
    String path = "";
    String Nic;
    String gen;
    int i;
    String newpath;
    File F;
    File F2;
    String pa;
    String date;
    String Fname;
    String Lname;

    byte Shedule_id;

    /**
     * Creates new form Add_members
     */
    public Add_members() {
        initComponents();
        jRadioButton1.setSelected(true);
        loadShed_to_Combo();
        jButton5_Save.setEnabled(false);
        jButton4_Update.setEnabled(false);
        jScrollPane3.setVisible(false);
        jList1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        txtNic = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        txtFname = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        txt_search = new javax.swing.JTextField();
        jButton2_search = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Image_Label = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4_Update = new javax.swing.JButton();
        jButton5_Save = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Last Name :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 60, 120, 21);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Nic :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 100, 120, 21);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Gender :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 140, 100, 21);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Address :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 180, 100, 21);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Shedule :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(380, 280, 120, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText(" Entrance Date :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(360, 20, 150, 21);

        jLabel9.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("First Name :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 20, 120, 21);

        txtLname.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txtLname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLnameKeyTyped(evt);
            }
        });
        jPanel1.add(txtLname);
        txtLname.setBounds(110, 60, 200, 28);

        txtNic.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txtNic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNicKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNicKeyTyped(evt);
            }
        });
        jPanel1.add(txtNic);
        txtNic.setBounds(110, 100, 200, 28);

        txtContact.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txtContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContactKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContactKeyTyped(evt);
            }
        });
        jPanel1.add(txtContact);
        txtContact.setBounds(110, 290, 200, 28);

        txtFname.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txtFname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFnameKeyTyped(evt);
            }
        });
        jPanel1.add(txtFname);
        txtFname.setBounds(110, 20, 200, 28);

        jComboBox1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "x", "v" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(310, 100, 40, 28);

        txtAddress.setColumns(20);
        txtAddress.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txtAddress.setRows(5);
        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAddressKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txtAddress);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(110, 170, 260, 111);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jRadioButton1.setText("Male");
        jRadioButton1.setContentAreaFilled(false);
        jRadioButton1.setFocusable(false);
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(110, 140, 80, 29);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jRadioButton2.setText("Female");
        jRadioButton2.setContentAreaFilled(false);
        jRadioButton2.setFocusable(false);
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(200, 140, 100, 29);

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jDateChooser1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(470, 20, 200, 28);

        jLabel13.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel13.setText(" Name :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(700, 60, 70, 21);

        jList1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jList1MousePressed(evt);
            }
        });
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jList1KeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jList1);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(760, 88, 220, 130);

        txt_search.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_searchKeyTyped(evt);
            }
        });
        jPanel1.add(txt_search);
        txt_search.setBounds(760, 60, 220, 28);

        jButton2_search.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jButton2_search.setText("Search");
        jButton2_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_searchActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2_search);
        jButton2_search.setBounds(870, 110, 130, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Mobile :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 290, 100, 21);

        Image_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Image_Chose_Label.png"))); // NOI18N
        Image_Label.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jPanel1.add(Image_Label);
        Image_Label.setBounds(480, 60, 160, 170);

        jButton1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(600, 240, 80, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 0, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(690, 20, 320, 170);

        jTable1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Nic", "Gender", "Address", "Mobile", "Entrance Date", "Shedule"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 330, 1000, 140);

        jButton3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jButton3.setText("Clear All");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(880, 480, 120, 30);

        jButton4_Update.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jButton4_Update.setText("Update");
        jButton4_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4_Update);
        jButton4_Update.setBounds(870, 290, 120, 30);

        jButton5_Save.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jButton5_Save.setText("Save");
        jButton5_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5_SaveActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5_Save);
        jButton5_Save.setBounds(730, 290, 130, 30);

        jButton6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jButton6.setText("Veiw All");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(740, 480, 130, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Image :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(370, 60, 110, 21);

        jComboBox2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jComboBox2.setFocusable(false);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(470, 280, 210, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {

            if (i == 10) {
                jButton5_Save.setEnabled(false);
            } else {
                jButton4_Update.setEnabled(false);
            }

            Image_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Image_Chose_Label.png")));
            System.gc();
            Class_Files.ImageSelect is = new Class_Files.ImageSelect();

            BufferedImage image = is.showDialog();

            path = is.getPath();
//////////////////////////////////////////////////////////////////////////////////
            newpath = path.replace("\\", "//");
            F = new File(newpath);
            String s = System.currentTimeMillis() + "";

            F2 = new File("C:\\Users\\Buwaneka\\Documents\\NetBeansProjects\\PROJECT_Gym\\Browsed_Images\\Employee\\" + s + ".jpg");
            System.out.println("C:\\Aruna_Gym\\Members\\");
            copyFile(F, F2);

            String pat = F2.getAbsolutePath();
            pa = pat.replace("\\", "//");

            ///////////////////////////////////////////////////////////////////////////////          
            File f1 = new File(pa);
            Image img = ImageIO.read(f1);

            img = img.getScaledInstance(Image_Label.getWidth(), Image_Label.getHeight(), java.awt.Image.SCALE_SMOOTH);

            Image_Label.setIcon(new ImageIcon(img));

            ///Validation
            if (path.equals("")) {
                jButton4_Update.setEnabled(false);
                jButton5_Save.setEnabled(false);

            } else {
                int date = jDateChooser1.getDate().toString().length();

                if (txtFname.getText().length() != 0
                        && txtLname.getText().length() != 0
                        && txtNic.getText().length() != 0
                        && jComboBox1.getSelectedIndex() != 0
                        && txtAddress.getText().length() != 0
                        && txtContact.getText().length() != 0
                        && date != 0
                        && jComboBox2.getSelectedIndex() != 0
                        && !path.equals("")) {

                    if (i == 100) {

                        jButton4_Update.setEnabled(true);
                    } else {

                        jButton5_Save.setEnabled(true);
                    }
                }

            }

        } catch (NullPointerException n) {
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5_SaveActionPerformed

        try {

            if (jRadioButton1.isSelected()) {
                gen = "Male";

            } else {
                gen = "Female";
            }
//////////////////////////////////////////////////////////*************
            Calendar ca = jDateChooser1.getCalendar();
            int Year = ca.get(Calendar.YEAR);
            int Month = ca.get(Calendar.MONTH);
            Month++;
            int Day = ca.get(Calendar.DATE);

            date = Year + "-" + Month + "-" + Day;
            ///////
            Nic = txtNic.getText() + " " + jComboBox1.getSelectedItem();

            //////Load Shed id
            ResultSet rs1 = DB.search("SELECT Shed_Id FROM shedule_reg WHERE Shedule = '" + jComboBox2.getSelectedItem().toString() + "' ");
            while (rs1.next()) {
                Shedule_id = Byte.parseByte(rs1.getString("Shed_Id"));

            }
///////////////////////////

            Class_Files.DB.sud("INSERT INTO members_reg(Shed_Id,First_Name,Last_Name,Nic,Gender,Address,Contact,Entrance_Date,Image,Status)VALUES('" + Shedule_id + "'"
                    + ",'" + txtFname.getText() + "'"
                    + ",'" + txtLname.getText() + "'"
                    + ",'" + Nic + "'"
                    + ",'" + gen + "'"
                    + ",'" + txtAddress.getText() + "'"
                    + ",'" + txtContact.getText() + "'"
                    + ", '" + date + "' "
                    + ", '" + pa + "'"
                    + ",'" + "On" + "')");

            JOptionPane.showMessageDialog(this, "Save Sucess");

            tabelAdd();
            EmtyTF();
            path = "";

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton5_SaveActionPerformed

    private void txtFnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFnameKeyTyped

        try {
            System.gc();

            char c = evt.getKeyChar();
            if (Character.isDigit(c) || c == 32) {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtFnameKeyTyped

    private void txtLnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLnameKeyTyped

        try {
            System.gc();

            char c = evt.getKeyChar();
            if (Character.isDigit(c) || c == 32) {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtLnameKeyTyped

    private void txt_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyTyped

        try {
            System.gc();

            char c = evt.getKeyChar();
            if (Character.isDigit(c) || c == 32) {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txt_searchKeyTyped

    private void txtNicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNicKeyTyped

        try {
            char c = evt.getKeyChar();
            int a = txtNic.getText().length();

            if (!Character.isDigit(c) || a > 8 || c == 32) {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtNicKeyTyped

    private void txtContactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactKeyTyped

        try {
            System.gc();
            int a = txtContact.getText().length();
            char c = evt.getKeyChar();

            if (!Character.isDigit(c) || a >= 10 || c == 32) {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtContactKeyTyped

    private void txtFnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFnameKeyReleased

        try {
            if (i == 100) {
                jButton5_Save.setEnabled(false);
            } else {
                jButton4_Update.setEnabled(false);
            }

            if (evt.getKeyCode() == 10) {
                txtLname.grabFocus();
            }

            if (txtFname.getText().length() == 0) {
                jButton4_Update.setEnabled(false);
                jButton5_Save.setEnabled(false);

            } else {
                int date = jDateChooser1.getDate().toString().length();

                if (txtFname.getText().length() != 0
                        && txtLname.getText().length() != 0
                        && txtNic.getText().length() != 0
                        && jComboBox1.getSelectedIndex() != 0
                        && txtAddress.getText().length() != 0
                        && txtContact.getText().length() != 0
                        && date != 0
                        && jComboBox2.getSelectedIndex() != 0
                        && !path.equals("")) {

                    if (i == 100) {

                        jButton4_Update.setEnabled(true);
                    } else {

                        jButton5_Save.setEnabled(true);
                    }
                }

            }

        } catch (NullPointerException e) {
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_txtFnameKeyReleased

    private void txtLnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLnameKeyReleased

        try {

            if (i == 100) {
                jButton5_Save.setEnabled(false);
            } else {
                jButton4_Update.setEnabled(false);
            }

            if (evt.getKeyCode() == 10) {
                txtNic.grabFocus();
            }

            if (txtLname.getText().length() == 0) {
                jButton4_Update.setEnabled(false);
                jButton5_Save.setEnabled(false);

            } else {
                int date = jDateChooser1.getDate().toString().length();

                if (txtFname.getText().length() != 0
                        && txtLname.getText().length() != 0
                        && txtNic.getText().length() != 0
                        && jComboBox1.getSelectedIndex() != 0
                        && txtAddress.getText().length() != 0
                        && txtContact.getText().length() != 0
                        && date != 0
                        && jComboBox2.getSelectedIndex() != 0
                        && !path.equals("")) {

                    if (i == 100) {

                        jButton4_Update.setEnabled(true);
                    } else {

                        jButton5_Save.setEnabled(true);
                    }
                }

            }

        } catch (NullPointerException e) {
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtLnameKeyReleased

    private void txtNicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNicKeyReleased

        try {

            if (i == 100) {
                jButton5_Save.setEnabled(false);
            } else {
                jButton4_Update.setEnabled(false);
            }

            if (evt.getKeyCode() == 10) {
                jComboBox1.grabFocus();
            }

            if (txtNic.getText().length() == 0) {
                jButton4_Update.setEnabled(false);
                jButton5_Save.setEnabled(false);

            } else {
                int date = jDateChooser1.getDate().toString().length();

                if (txtFname.getText().length() != 0
                        && txtLname.getText().length() != 0
                        && txtNic.getText().length() != 0
                        && jComboBox1.getSelectedIndex() != 0
                        && txtAddress.getText().length() != 0
                        && txtContact.getText().length() != 0
                        && date != 0
                        && jComboBox2.getSelectedIndex() != 0
                        && !path.equals("")) {

                    if (i == 100) {

                        jButton4_Update.setEnabled(true);
                    } else {

                        jButton5_Save.setEnabled(true);
                    }
                }

            }

        } catch (NullPointerException e) {
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtNicKeyReleased

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        try {

            if (i == 100) {
                jButton5_Save.setEnabled(false);
            } else {
                jButton4_Update.setEnabled(false);
            }

            if (jComboBox1.getSelectedIndex() == 0) {
                jButton4_Update.setEnabled(false);
                jButton5_Save.setEnabled(false);

            } else {
                int date = jDateChooser1.getDate().toString().length();

                if (txtFname.getText().length() != 0
                        && txtLname.getText().length() != 0
                        && txtNic.getText().length() != 0
                        && jComboBox1.getSelectedIndex() != 0
                        && txtAddress.getText().length() != 0
                        && txtContact.getText().length() != 0
                        && date != 0
                        && jComboBox2.getSelectedIndex() != 0
                        && !path.equals("")) {

                    if (i == 100) {

                        jButton4_Update.setEnabled(true);
                    } else {

                        jButton5_Save.setEnabled(true);
                    }
                }

            }

        } catch (NullPointerException n) {
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyReleased

        try {
            if (i == 100) {
                jButton5_Save.setEnabled(false);
            } else {
                jButton4_Update.setEnabled(false);
            }

            if (evt.getKeyCode() == 10) {
                txtContact.grabFocus();
            }

            if (txtAddress.getText().length() == 0) {
                jButton4_Update.setEnabled(false);
                jButton5_Save.setEnabled(false);

            } else {
                int date = jDateChooser1.getDate().toString().length();

                if (txtFname.getText().length() != 0
                        && txtLname.getText().length() != 0
                        && txtNic.getText().length() != 0
                        && jComboBox1.getSelectedIndex() != 0
                        && txtAddress.getText().length() != 0
                        && txtContact.getText().length() != 0
                        && date != 0
                        && jComboBox2.getSelectedIndex() != 0
                        && !path.equals("")) {

                    if (i == 100) {

                        jButton4_Update.setEnabled(true);
                    } else {

                        jButton5_Save.setEnabled(true);
                    }
                }

            }

            /////////////////////////////////////////
        } catch (NullPointerException e) {
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtAddressKeyReleased

    private void txtContactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactKeyReleased

        try {

            if (i == 100) {
                jButton5_Save.setEnabled(false);
            } else {
                jButton4_Update.setEnabled(false);
            }

            if (txtContact.getText().length() == 0) {
                jButton4_Update.setEnabled(false);
                jButton5_Save.setEnabled(false);

            } else {
                int date = jDateChooser1.getDate().toString().length();

                if (txtFname.getText().length() != 0
                        && txtLname.getText().length() != 0
                        && txtNic.getText().length() != 0
                        && jComboBox1.getSelectedIndex() != 0
                        && txtAddress.getText().length() != 0
                        && txtContact.getText().length() != 0
                        && date != 0
                        && jComboBox2.getSelectedIndex() != 0
                        && !path.equals("")) {

                    if (i == 100) {

                        jButton4_Update.setEnabled(true);
                    } else {

                        jButton5_Save.setEnabled(true);
                    }
                }

            }

        } catch (NullPointerException e) {
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtContactKeyReleased

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange

        try {

            if (i == 100) {
                jButton5_Save.setEnabled(false);
            } else {
                jButton4_Update.setEnabled(false);
            }

            int date = jDateChooser1.getDate().toString().length();
            if (date == 0) {
                jButton4_Update.setEnabled(false);
                jButton5_Save.setEnabled(false);

            } else {

                if (txtFname.getText().length() != 0
                        && txtLname.getText().length() != 0
                        && txtNic.getText().length() != 0
                        && jComboBox1.getSelectedIndex() != 0
                        && txtAddress.getText().length() != 0
                        && txtContact.getText().length() != 0
                        && date != 0
                        && jComboBox2.getSelectedIndex() != 0
                        && !path.equals("")) {

                    if (i == 100) {

                        jButton4_Update.setEnabled(true);
                    } else {

                        jButton5_Save.setEnabled(true);
                    }
                }

            }

        } catch (NullPointerException e) {
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jDateChooser1PropertyChange

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed

        try {

            if (i == 100) {
                jButton5_Save.setEnabled(false);
            } else {
                jButton4_Update.setEnabled(false);
            }

            if (jComboBox2.getSelectedIndex() == 0) {
                jButton4_Update.setEnabled(false);
                jButton5_Save.setEnabled(false);

            } else {
                int date = jDateChooser1.getDate().toString().length();

                if (txtFname.getText().length() != 0
                        && txtLname.getText().length() != 0
                        && txtNic.getText().length() != 0
                        && jComboBox1.getSelectedIndex() != 0
                        && txtAddress.getText().length() != 0
                        && txtContact.getText().length() != 0
                        && date != 0
                        && jComboBox2.getSelectedIndex() != 0
                        && !path.equals("")) {

                    if (i == 100) {

                        jButton4_Update.setEnabled(true);
                    } else {

                        jButton5_Save.setEnabled(true);
                    }
                }

            }

        } catch (NullPointerException e) {
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased

        try {

            if (!txt_search.getText().trim().equals("")) {
                ResultSet rs = Class_Files.DB.search("SELECT * FROM members_reg WHERE First_Name LIKE '" + txt_search.getText() + "%' || Last_Name LIKE '" + txt_search.getText() + "%' ");
                Vector v = new Vector();
                jList1.removeAll();

                while (rs.next()) {

                    String sts = rs.getString("Status");

                    if (sts.equals("On")) {

                        jScrollPane3.setVisible(true);
                        jList1.setVisible(true);
                        jButton2_search.setEnabled(true);

                        String Fn = rs.getString("First_Name");
                        String Ln = rs.getString("Last_Name");
                        v.add(Fn + " " + Ln);
                        jList1.setListData(v);

                    }

                }

            } else {
                jScrollPane3.setVisible(false);
                jList1.setVisible(false);
                jButton2_search.setEnabled(false);

            }

            /////////////////////////////////////////////////////////
            if (jList1.isVisible()) {
                if (evt.getKeyCode() == 40) {
                    jList1.grabFocus();
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txt_searchKeyReleased

    private void jList1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyReleased

        try {
            System.gc();
            if (evt.getKeyCode() == 10) {
                txt_search.setText(jList1.getSelectedValue().toString());
                jScrollPane3.setVisible(false);
                jList1.setVisible(false);
                jButton2_search.grabFocus();

            }
        } catch (NullPointerException e) {

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jList1KeyReleased

    private void jList1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MousePressed

        try {
            System.gc();
            if (evt.getClickCount() == 2) {
                txt_search.setText(jList1.getSelectedValue().toString());
                jScrollPane3.setVisible(false);
                jList1.setVisible(false);

            }

        } catch (NullPointerException n) {
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jList1MousePressed

    private void jButton2_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_searchActionPerformed

        try {
            if (!txt_search.getText().equals("")) {

                byte d = 0;

                String Name[] = txt_search.getText().split(" ");
                DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                dtm.setRowCount(0);
                Vector v = new Vector();
                ResultSet rs = Class_Files.DB.search("SELECT * FROM members_reg WHERE First_Name = '" + Name[0] + "' && Last_Name='" + Name[1] + "' ");
                while (rs.next()) {
                    d = 1;
                    v.add(rs.getString("First_Name"));
                    v.add(rs.getString("Last_Name"));
                    v.add(rs.getString("Nic"));
                    v.add(rs.getString("Gender"));
                    v.add(rs.getString("Address"));
                    v.add(rs.getString("Contact"));
                    v.add(rs.getString("Entrance_Date"));

                    ResultSet rs1 = DB.search("SELECT * FROM shedule_reg WHERE Shed_Id = '" + rs.getString("Shed_Id") + "' ");
                    while (rs1.next()) {
                        String Shedule = rs1.getString("Shedule");
                        v.add(Shedule);
                    }

                    dtm.addRow(v);
                }

                if (d == 0) {
                    JOptionPane.showMessageDialog(this, "Sorry No result found..!");
                }

                txt_search.setText("");
                jButton2_search.setEnabled(false);
            }

        } catch (ArrayIndexOutOfBoundsException a) {
            JOptionPane.showMessageDialog(this, "Sorry this name cannot search..!");

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton2_searchActionPerformed
    int Memid = 0;
    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed

        try {
            System.gc();
            if (evt.getButton() == 1) {
//**********************************************///

                if (evt.getClickCount() == 2) {
                    i = 100;
                    int row = jTable1.getSelectedRow();
                    path = " ";

                    Fname = jTable1.getValueAt(row, 0).toString();
                    Lname = jTable1.getValueAt(row, 1).toString();
                    String Nic[] = jTable1.getValueAt(row, 2).toString().split(" ");
                    String Gen = jTable1.getValueAt(row, 3).toString();
                    String Add = jTable1.getValueAt(row, 4).toString();
                    String Cont = jTable1.getValueAt(row, 5).toString();
                    String Tdate = jTable1.getValueAt(row, 6).toString();
                    String Shed = jTable1.getValueAt(row, 7).toString();

                    DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                    Date D = df.parse(Tdate);

                    txtFname.setText(Fname);
                    txtLname.setText(Lname);
                    txtNic.setText(Nic[0]);
                    jComboBox1.setSelectedItem(Nic[1]);

                    if (Gen.equals("Male")) {
                        jRadioButton1.setSelected(true);
                    } else {
                        jRadioButton2.setSelected(true);
                    }

                    txtAddress.setText(Add);
                    txtContact.setText(Cont);
                    jDateChooser1.setDate(D);
                    jComboBox2.setSelectedItem(Shed);

                    ResultSet rs = Class_Files.DB.search("SELECT * FROM members_reg WHERE First_Name = '" + Fname + "' && Last_Name='" + Lname + "' ");
                    while (rs.next()) {
                        Memid = rs.getInt("Mem_Id");
                        String imagedata = rs.getString("Image");
                        File f = new File(imagedata);
                        Image img = ImageIO.read(f);
                        img = img.getScaledInstance(Image_Label.getWidth(), Image_Label.getHeight(), java.awt.Image.SCALE_SMOOTH);
                        Image_Label.setIcon(new ImageIcon(img));

                    }

                    ///Load Member ID
                    //
                    jButton4_Update.setEnabled(true);
                } else {
                    int ro = jTable1.getSelectedRow();
                    Fname = jTable1.getValueAt(ro, 0).toString();
                    Lname = jTable1.getValueAt(ro, 1).toString();

                    ResultSet rs2 = Class_Files.DB.search("SELECT * FROM members_reg WHERE First_Name = '" + Fname + "' && Last_Name='" + Lname + "' ");
                    while (rs2.next()) {
                        Memid = rs2.getInt("Mem_Id");
                    }
                }

//******************************************************////
            }

            ///If Right Click   
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();

            if (jTable1.isRowSelected(jTable1.getSelectedRow())) {

                Rc_1 rc1 = null;

                if (evt.getButton() == 3) {
                    rc1 = new Rc_1(x, y, new javax.swing.JFrame(), true);
                    rc1.memid = Memid;
                    rc1.setVisible(true);
                } else {
                    rc1 = new Rc_1(x, y, new javax.swing.JFrame(), true);
                    rc1.dispose();

                }
            } else {

                Rc_1 rc = new Rc_1(x, y, new javax.swing.JFrame(), true);
                rc.setVisible(false);
                rc.dispose();
            }

        } catch (NullPointerException n) {
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jTable1MousePressed

    private void jButton4_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_UpdateActionPerformed

        try {

            int Mid = 0;
            ResultSet rs = Class_Files.DB.search("SELECT Mem_Id FROM members_reg WHERE First_Name='" + Fname + "' && Last_Name='" + Lname + "' ");
            while (rs.next()) {
                Mid = Integer.parseInt(rs.getString("Mem_Id"));
            }

///////////////////////////////
            if (jRadioButton1.isSelected()) {
                gen = "Male";

            } else {
                gen = "Female";
            }
//////////////////////////////////////////////////////////*************
            Calendar ca = jDateChooser1.getCalendar();
            int Year = ca.get(Calendar.YEAR);
            int Month = ca.get(Calendar.MONTH);
            Month++;
            int Day = ca.get(Calendar.DATE);

            date = Year + "-" + Month + "-" + Day;
            ///////
            Nic = txtNic.getText() + " " + jComboBox1.getSelectedItem();

            //////Load Shed id
            ResultSet rs1 = DB.search("SELECT Shed_Id FROM shedule_reg WHERE Shedule = '" + jComboBox2.getSelectedItem().toString() + "' ");
            while (rs1.next()) {
                Shedule_id = Byte.parseByte(rs1.getString("Shed_Id"));

            }

            if (!path.equals(" ")) {

                Class_Files.DB.sud(" UPDATE members_reg SET Shed_Id = '" + Shedule_id + "'"
                        + ", First_Name = '" + txtFname.getText() + "' "
                        + ", Last_Name= '" + txtLname.getText() + "' "
                        + ", Nic = '" + Nic + "'"
                        + ", Gender = '" + gen + "' "
                        + ", Address = '" + txtAddress.getText() + "' "
                        + ", Contact = '" + txtContact.getText() + "' "
                        + ", Entrance_Date = '" + date + "' "
                        + ",Image = '" + pa + "'  WHERE Mem_id = '" + Mid + "' ");

            } else {

                Class_Files.DB.sud(" UPDATE members_reg SET Shed_Id = '" + Shedule_id + "'"
                        + ",  First_Name = '" + txtFname.getText() + "' "
                        + ", Last_Name= '" + txtLname.getText() + "' "
                        + ", Nic = '" + Nic + "'"
                        + ", Gender = '" + gen + "' "
                        + ", Address = '" + txtAddress.getText() + "' "
                        + ", Contact = '" + txtContact.getText() + "' "
                        + ", Entrance_Date = '" + date + "'  WHERE Mem_id = '" + Mid + "' ");

            }

            path = "";
            i = 0;
            tabelAdd();
            EmtyTF();

            JOptionPane.showMessageDialog(this, "Update Success..!");

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton4_UpdateActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try {
            EmtyTF();
            txt_search.setText("");
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            path = "";
            i = 0;
            jButton2_search.setEnabled(false);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        try {

            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            ResultSet rs = Class_Files.DB.search("SELECT * FROM members_reg ");
            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString("First_Name"));
                v.add(rs.getString("Last_Name"));
                v.add(rs.getString("Nic"));
                v.add(rs.getString("Gender"));
                v.add(rs.getString("Address"));
                v.add(rs.getString("Contact"));
                v.add(rs.getString("Entrance_Date"));

                ResultSet rs1 = DB.search("SELECT * FROM shedule_reg WHERE Shed_Id = '" + rs.getString("Shed_Id") + "' ");
                while (rs1.next()) {
                    String Shedule = rs1.getString("Shedule");
                    v.add(Shedule);
                }

                dtm.addRow(v);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Image_Label;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2_search;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4_Update;
    private javax.swing.JButton jButton5_Save;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtNic;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables

    public static void copyFile(File sourceFile, File destFile) throws IOException {

        if (!destFile.exists()) {
            destFile.createNewFile();
        }
        FileInputStream fIn = null;
        FileOutputStream fOut = null;
        FileChannel source = null;
        FileChannel destination = null;
        try {
            fIn = new FileInputStream(sourceFile);
            source = fIn.getChannel();
            fOut = new FileOutputStream(destFile);
            destination = fOut.getChannel();
            long transfered = 0;
            long bytes = source.size();
            while (transfered < bytes) {
                transfered += destination.transferFrom(source, 0, source.size());
                destination.position(transfered);
            }
        } finally {
            if (source != null) {
                source.close();
            } else if (fIn != null) {
                fIn.close();
            }
            if (destination != null) {
                destination.close();
            } else if (fOut != null) {
                fOut.close();
            }
        }

    }

    private void loadShed_to_Combo() {

        try {

            ResultSet rs = DB.search("SELECT Shedule From shedule_reg");
            DefaultComboBoxModel dcm = (DefaultComboBoxModel) jComboBox2.getModel();
            dcm.removeAllElements();
            dcm.addElement(" ");
            while (rs.next()) {

                dcm.addElement(rs.getString("Shedule"));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void tabelAdd() throws Exception {

        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        Vector v = new Vector();
        v.add(txtFname.getText());
        v.add(txtLname.getText());
        v.add(Nic);
        v.add(gen);
        v.add(txtAddress.getText());
        v.add(txtContact.getText());
        v.add(date);
        v.add(jComboBox2.getSelectedItem());

        dtm.addRow(v);

    }

    public void EmtyTF() throws Exception {
        txtFname.setText("");
        txtLname.setText("");
        txtNic.setText("");
        jComboBox1.setSelectedIndex(0);
        jRadioButton1.setSelected(true);
        txtAddress.setText("");
        txtContact.setText("");
        jDateChooser1.setDate(null);
        jComboBox2.setSelectedIndex(0);
        Image_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Image_Chose_Label.png")));
        jButton5_Save.setEnabled(false);
        jButton4_Update.setEnabled(false);

        path = "";
        i = 0;

    }

}
