/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin.FPlan;

import Class_Files.DB;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Buwaneka
 */
public class Workout_Shedule_Reg extends javax.swing.JPanel {

    byte Shedule_id;
    byte work_id;
    int i;
    String workout;

    /**
     * Creates new form Workout_Shedule_Reg
     */
    public Workout_Shedule_Reg() {
        initComponents();
        jScrollPane3.setVisible(false);
        jList1.setVisible(false);

        jScrollPane4.setVisible(false);
        jList2.setVisible(false);

        jButton_Save_Workout.setEnabled(false);
        jButton_Update_workout.setEnabled(false);
        jButton2_search.setEnabled(false);
        jButton_Save_Shedule.setEnabled(false);
        jButton_add.setEnabled(false);
        loadShed_to_Combo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        txtSerach = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDes = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jButton3 = new javax.swing.JButton();
        jButton2_search = new javax.swing.JButton();
        txtWname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton_add = new javax.swing.JButton();
        jButton_Update_workout = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton_Save_Shedule = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtSearch_Workout_for_Shed = new javax.swing.JTextField();
        jButton_Save_Workout = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtSheduleName = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton_Update_workout1 = new javax.swing.JButton();
        jButton_Update_workout2 = new javax.swing.JButton();
        jButton_Update_workout3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtSerach1 = new javax.swing.JTextField();
        jButton2_search1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(550, 20, 20, 490);

        jList3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
        jScrollPane6.setViewportView(jList3);

        jPanel1.add(jScrollPane6);
        jScrollPane6.setBounds(700, 204, 200, 80);

        jLabel9.setFont(new java.awt.Font("Segoe UI Semilight", 0, 17)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Workouts adding For Shedule");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(572, 250, 240, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
        jLabel1.setText("Workout :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(630, 310, 80, 40);

        jList1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jList1MousePressed(evt);
            }
        });
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jList1KeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jList1);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(160, 285, 200, 100);

        txtSerach.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txtSerach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSerachKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSerachKeyTyped(evt);
            }
        });
        jPanel1.add(txtSerach);
        txtSerach.setBounds(160, 260, 200, 25);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
        jLabel2.setText("Workout Name :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 60, 130, 20);

        txtDes.setColumns(20);
        txtDes.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txtDes.setRows(5);
        txtDes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDesKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDesKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtDes);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(160, 90, 310, 90);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Workout Name", "Description"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 360, 510, 110);

        jButton6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jButton6.setText("Veiw All");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(320, 480, 90, 28);

        jList2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jList2MousePressed(evt);
            }
        });
        jList2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jList2KeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(jList2);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(700, 345, 250, 90);

        jButton3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jButton3.setText("Clear All");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(420, 480, 100, 28);

        jButton2_search.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jButton2_search.setText("Search");
        jButton2_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_searchActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2_search);
        jButton2_search.setBounds(370, 260, 90, 25);

        txtWname.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txtWname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtWnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtWnameKeyTyped(evt);
            }
        });
        jPanel1.add(txtWname);
        txtWname.setBounds(160, 60, 270, 25);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
        jLabel4.setText("Description :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 100, 130, 20);

        jButton_add.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jButton_add.setText("Add");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_add);
        jButton_add.setBounds(780, 360, 100, 28);

        jButton_Update_workout.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jButton_Update_workout.setText("Delete");
        jButton_Update_workout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Update_workoutActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Update_workout);
        jButton_Update_workout.setBounds(410, 190, 100, 25);

        jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 0, 17)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Workout Register");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 10, 140, 30);

        jButton_Save_Shedule.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jButton_Save_Shedule.setText("Save");
        jButton_Save_Shedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Save_SheduleActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Save_Shedule);
        jButton_Save_Shedule.setBounds(710, 95, 90, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
        jLabel5.setText("Shedule Name :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(575, 60, 110, 20);

        txtSearch_Workout_for_Shed.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txtSearch_Workout_for_Shed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearch_Workout_for_ShedKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearch_Workout_for_ShedKeyTyped(evt);
            }
        });
        jPanel1.add(txtSearch_Workout_for_Shed);
        txtSearch_Workout_for_Shed.setBounds(700, 320, 250, 25);

        jButton_Save_Workout.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jButton_Save_Workout.setText("Save");
        jButton_Save_Workout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Save_WorkoutActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Save_Workout);
        jButton_Save_Workout.setBounds(190, 190, 100, 25);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(580, 132, 440, 20);

        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 17)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Shedule Register");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(572, 10, 160, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
        jLabel6.setText("Workout Name :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 260, 110, 20);

        jComboBox2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Trainer", "Other" }));
        jComboBox2.setFocusable(false);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(700, 290, 250, 25);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
        jLabel7.setText("Shedule :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(630, 290, 80, 20);

        txtSheduleName.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txtSheduleName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSheduleNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSheduleNameKeyTyped(evt);
            }
        });
        jPanel1.add(txtSheduleName);
        txtSheduleName.setBounds(680, 60, 230, 25);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Work out"
            }
        ));
        jScrollPane5.setViewportView(jTable2);

        jPanel1.add(jScrollPane5);
        jScrollPane5.setBounds(570, 400, 440, 90);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 0, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 220, 470, 110);

        jButton4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jButton4.setText("Clear All");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(890, 360, 90, 28);

        jButton_Update_workout1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jButton_Update_workout1.setText("Update");
        jButton_Update_workout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Update_workout1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Update_workout1);
        jButton_Update_workout1.setBounds(300, 190, 100, 25);

        jButton_Update_workout2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jButton_Update_workout2.setText("Update");
        jButton_Update_workout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Update_workout2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Update_workout2);
        jButton_Update_workout2.setBounds(810, 95, 100, 25);

        jButton_Update_workout3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jButton_Update_workout3.setText("Delete");
        jButton_Update_workout3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Update_workout3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Update_workout3);
        jButton_Update_workout3.setBounds(920, 95, 100, 25);

        jLabel12.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
        jLabel12.setText("Shedule Name :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(590, 180, 110, 20);

        txtSerach1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txtSerach1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSerach1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSerach1KeyTyped(evt);
            }
        });
        jPanel1.add(txtSerach1);
        txtSerach1.setBounds(700, 180, 200, 25);

        jButton2_search1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jButton2_search1.setText("Search");
        jButton2_search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_search1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2_search1);
        jButton2_search1.setBounds(910, 180, 80, 25);

        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 0, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(560, 140, 470, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSerachKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerachKeyReleased

        try {

            if (!txtSerach.getText().trim().equals("")) {
                ResultSet rs = Class_Files.DB.search("SELECT * FROM Workout_reg WHERE Workout LIKE '" + txtSerach.getText() + "%'");
                Vector v = new Vector();
                jList1.removeAll();

                while (rs.next()) {

                    String sts = rs.getString("Status");

                    if (sts.equals("On")) {

                        jScrollPane3.setVisible(true);
                        jList1.setVisible(true);
                        jButton2_search.setEnabled(true);

                        v.add(rs.getString("Workout"));
                        jList1.setListData(v);

                    }

                }

            } else {
                jScrollPane3.setVisible(false);
                jList1.setVisible(false);
                jButton2_search.setEnabled(false);

            }

            /////////////////////////////////////////////////////////
            if (jList1.isVisible()) {
                if (evt.getKeyCode() == 40) {
                    jList1.grabFocus();
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtSerachKeyReleased

    private void txtSerachKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerachKeyTyped

        try {
            System.gc();

            char c = evt.getKeyChar();
            if (Character.isDigit(c) || c == 32) {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtSerachKeyTyped

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed

        try {

            byte a = 0;
            byte b = 0;
            ResultSet rs = DB.search("SELECT * FROM workout_reg");
            while (rs.next()) {

                if (rs.getString("Workout").toLowerCase().equals(txtSearch_Workout_for_Shed.getText().toLowerCase())) {
                    a = 1;
                }

            }

            if (a == 0) {
                JOptionPane.showMessageDialog(this, "Sorry this workout not availabe..!", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {

                ResultSet rs1 = DB.search("SELECT Shed_Id FROM shedule_reg WHERE Shedule = '" + jComboBox2.getSelectedItem().toString() + "' ");
                while (rs1.next()) {
                    Shedule_id = Byte.parseByte(rs1.getString("Shed_Id"));

                }
                ////////////////////////////////////
                ResultSet rs2 = DB.search("SELECT W_Id FROM workout_reg WHERE Workout = '" + txtSearch_Workout_for_Shed.getText() + "' ");
                while (rs2.next()) {
                    work_id = Byte.parseByte(rs2.getString("W_Id"));

                }

                ///////////////Api danna yana work out eka kalin Shedule ekata dala tiyanwada balanwa/////////// 
                ResultSet rs3 = DB.search("SELECT * FROM shedule_reg_has_workout WHERE Shed_Id='" + Shedule_id + "' ");
                while (rs3.next()) {

                    if (rs3.getInt("W_id") == work_id) {
                        b = 1;

                    }

                }
                /////////////////////////////////////////////////////////////////

                //if dala tiyanwa nam
                if (b == 1) {
                    JOptionPane.showMessageDialog(this, "This workout already added to " + jComboBox2.getSelectedItem() + " Shedule ", "Warning", JOptionPane.WARNING_MESSAGE);

                } else {

                    //if dala nattam
                    Class_Files.DB.sud("INSERT INTO shedule_reg_has_workout(Shed_Id,W_Id)VALUES('" + Shedule_id + "' , '" + work_id + "')");
                    JOptionPane.showMessageDialog(this, "Added Sucess..!");

                    jComboBox2.setSelectedIndex(0);
                    txtSearch_Workout_for_Shed.setText("");
                    loadShed_to_Combo();
                }

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton_addActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {

            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            ResultSet rs = Class_Files.DB.search("SELECT * FROM Workout_reg ");
            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString("Workout"));
                v.add(rs.getString("Des"));
                dtm.addRow(v);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try {
            System.gc();
            EmptyTF();
            DefaultTableModel ftm = (DefaultTableModel) jTable1.getModel();
            ftm.setRowCount(0);
            i = 0;
            txtSerach.setText("");

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtWnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWnameKeyReleased

        try {
            if (txtWname.getText().length() == 0) {
                jButton_Save_Workout.setEnabled(false);
                jButton_Update_workout.setEnabled(false);
            } else {

                if (txtWname.getText().length() != 0
                        && txtDes.getText().length() != 0) {

                    jButton_Save_Workout.setEnabled(true);
                    jButton_Update_workout.setEnabled(true);

                } else {
                    jButton_Save_Workout.setEnabled(false);
                    jButton_Update_workout.setEnabled(false);
                }

            }

            /////////////////////////////////////////
            if (i == 10) {
                jButton_Save_Workout.setEnabled(false);
            } else {
                jButton_Update_workout.setEnabled(false);
            }

            if (evt.getKeyCode() == 10) {
                txtDes.grabFocus();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtWnameKeyReleased

    private void txtWnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWnameKeyTyped

        try {
            System.gc();

            char c = evt.getKeyChar();
            if (Character.isDigit(c) || c == 32) {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtWnameKeyTyped

    private void jButton2_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_searchActionPerformed

        try {
            if (!txtSerach.getText().equals("")) {

                byte d = 0;

                DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                dtm.setRowCount(0);
                Vector v = new Vector();
                ResultSet rs = Class_Files.DB.search("SELECT * FROM Workout_reg WHERE Workout = '" + txtSerach.getText() + "' ");
                while (rs.next()) {
                    d = 1;
                    v.add(rs.getString("Workout"));
                    v.add(rs.getString("Des"));
                    dtm.addRow(v);
                }

                if (d == 0) {
                    JOptionPane.showMessageDialog(this, "Sorry No result found..!");
                }

                txtSerach.setText("");
                jButton2_search.setEnabled(false);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton2_searchActionPerformed

    private void jButton_Update_workoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Update_workoutActionPerformed
        try {

            int Wid = 0;
            ResultSet rs = Class_Files.DB.search("SELECT W_Id FROM Workout_reg WHERE Workout='" + workout + "' ");
            while (rs.next()) {
                Wid = Integer.parseInt(rs.getString("W_Id"));
            }

            Class_Files.DB.sud("Update Workout_reg SET Workout = '" + txtWname.getText() + "' "
                    + ", Des = '" + txtDes.getText() + "'  WHERE W_id = '" + Wid + "'  ");
            i = 0;
            TabelAdd();
            EmptyTF();
            JOptionPane.showMessageDialog(this, "Workout Update Sucess..!");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton_Update_workoutActionPerformed

    private void txtSearch_Workout_for_ShedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearch_Workout_for_ShedKeyReleased

        try {

            if (!txtSearch_Workout_for_Shed.getText().trim().equals("")) {
                ResultSet rs = Class_Files.DB.search("SELECT * FROM Workout_reg WHERE Workout LIKE '" + txtSearch_Workout_for_Shed.getText() + "%'");
                Vector v = new Vector();
                jList2.removeAll();

                while (rs.next()) {

                    String sts = rs.getString("Status");

                    if (sts.equals("On")) {

                        jScrollPane4.setVisible(true);
                        jList2.setVisible(true);
                        jButton_add.setEnabled(true);

                        v.add(rs.getString("Workout"));
                        jList2.setListData(v);

                    }

                }

            } else {
                jScrollPane4.setVisible(false);
                jList2.setVisible(false);
                jButton_add.setEnabled(false);

            }

            /////Button Validation
            if (txtSearch_Workout_for_Shed.getText().length() == 0) {
                jButton_add.setEnabled(false);
            } else {

                if (jComboBox2.getSelectedIndex() != 0
                        && txtSearch_Workout_for_Shed.getText().length() != 0) {

                    jButton_add.setEnabled(true);

                } else {

                    jButton_add.setEnabled(false);
                }

            }

            //////////////////////////////////////////
            /////////////////////////////////////////////////////////
            if (jList2.isVisible()) {
                if (evt.getKeyCode() == 40) {
                    jList2.grabFocus();
                }
            }

            if (evt.getKeyCode() == 10) {
                jButton_add.grabFocus();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtSearch_Workout_for_ShedKeyReleased

    private void txtSearch_Workout_for_ShedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearch_Workout_for_ShedKeyTyped

        try {
            System.gc();

            char c = evt.getKeyChar();
            if (Character.isDigit(c) || c == 32) {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtSearch_Workout_for_ShedKeyTyped

    private void jButton_Save_WorkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Save_WorkoutActionPerformed

        try {
// Cheack Workout already Avalable?

            String wkout = txtWname.getText().toLowerCase();
            byte a = 0;
            ResultSet rs = DB.search("SELECT * FROM workout_reg");
            while (rs.next()) {

                if (wkout.equals(rs.getString("Workout").toLowerCase())) {
                    ++a;
                }

            }
            ///////////////////////////////////////////////////////////////////////////////////      
            if (a != 0) {

                JOptionPane.showMessageDialog(this, "Sorry this workout already Availabe", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {

                Class_Files.DB.sud("INSERT INTO workout_reg(Workout,Des,Status)VALUES('" + txtWname.getText() + "'"
                        + ", '" + txtDes.getText() + "', '" + "On" + "')");

                TabelAdd();
                EmptyTF();
                JOptionPane.showMessageDialog(this, "Workout Save Sucess..!");

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton_Save_WorkoutActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed

        try {
            if (jComboBox2.getSelectedIndex() == 0) {
                jButton_add.setEnabled(false);
            } else {

                if (jComboBox2.getSelectedIndex() != 0
                        && txtSearch_Workout_for_Shed.getText().length() != 0) {

                    jButton_add.setEnabled(true);

                } else {

                    jButton_add.setEnabled(false);
                }

            }

            Load_workouts(jComboBox2.getSelectedItem());

            //////////////////////////////////////////
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void txtSheduleNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSheduleNameKeyReleased

        try {

            if (txtSheduleName.getText().length() == 0) {
                jButton_Save_Shedule.setEnabled(false);
            } else {

                if (txtSheduleName.getText().length() != 0) {

                    jButton_Save_Shedule.setEnabled(true);

                } else {
                    jButton_Save_Shedule.setEnabled(false);
                }

            }

            if (evt.getKeyCode() == 10) {
                jButton_Save_Shedule.grabFocus();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtSheduleNameKeyReleased

    private void txtSheduleNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSheduleNameKeyTyped

        try {
            System.gc();

            char c = evt.getKeyChar();
            if (Character.isDigit(c) || c == 32) {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtSheduleNameKeyTyped

    private void jButton_Save_SheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Save_SheduleActionPerformed

        try {
            String Shed = txtSheduleName.getText().toLowerCase().trim();
            byte a = 0;
            ResultSet rs = DB.search("SELECT * FROM shedule_reg");
            while (rs.next()) {

                if (Shed.equals(rs.getString("Shedule").toLowerCase())) {
                    ++a;
                }
            }
/////////////////////////////////////////////
            if (a != 0) {

                JOptionPane.showMessageDialog(this, "Sorry this Shedule already Availabe", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {

                Class_Files.DB.sud("INSERT INTO shedule_reg(Shedule,Status)VALUES('" + txtSheduleName.getText() + "'"
                        + ", '" + "On" + "')");

                txtSheduleName.setText("");
                jButton_Save_Shedule.setEnabled(false);
                JOptionPane.showMessageDialog(this, "Shedule Save Sucess..!");
                loadShed_to_Combo();

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton_Save_SheduleActionPerformed

    private void txtDesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDesKeyTyped

        try {
            System.gc();

            char c = evt.getKeyChar();
            if (Character.isDigit(c)) {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtDesKeyTyped

    private void txtDesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDesKeyReleased

        try {
            if (txtDes.getText().length() == 0) {
                jButton_Save_Workout.setEnabled(false);
                jButton_Update_workout.setEnabled(false);
            } else {

                if (txtWname.getText().length() != 0
                        && txtDes.getText().length() != 0) {

                    jButton_Save_Workout.setEnabled(true);
                    jButton_Update_workout.setEnabled(true);

                } else {
                    jButton_Save_Workout.setEnabled(false);
                    jButton_Update_workout.setEnabled(false);
                }

            }

            /////////////////////////////////////////
            if (i == 10) {
                jButton_Save_Workout.setEnabled(false);
            } else {
                jButton_Update_workout.setEnabled(false);
            }

            if (evt.getKeyCode() == 10) {
                jButton_Save_Workout.grabFocus();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtDesKeyReleased

    private void jList1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyReleased

        try {
            System.gc();
            if (evt.getKeyCode() == 10) {
                txtSerach.setText(jList1.getSelectedValue().toString());
                jScrollPane3.setVisible(false);
                jList1.setVisible(false);
                jButton2_search.grabFocus();

            }
        } catch (NullPointerException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jList1KeyReleased

    private void jList1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MousePressed

        try {

            System.gc();
            if (evt.getClickCount() == 2) {
                txtSerach.setText(jList1.getSelectedValue().toString());
                jScrollPane3.setVisible(false);
                jList1.setVisible(false);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jList1MousePressed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed

        try {
            System.gc();
            i = 10;
            int row = jTable1.getSelectedRow();

            workout = jTable1.getValueAt(row, 0).toString();
            String Des = jTable1.getValueAt(row, 1).toString();

            txtWname.setText(workout);
            txtDes.setText(Des);

            jButton_Update_workout.setEnabled(true);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jTable1MousePressed

    private void jList2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList2KeyReleased

        try {
            System.gc();
            if (evt.getKeyCode() == 10) {
                txtSearch_Workout_for_Shed.setText(jList2.getSelectedValue().toString());
                jScrollPane4.setVisible(false);
                jList2.setVisible(false);
                jButton_add.grabFocus();

            }
        } catch (NullPointerException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jList2KeyReleased

    private void jList2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MousePressed
        try {

            System.gc();
            if (evt.getClickCount() == 2) {
                txtSearch_Workout_for_Shed.setText(jList2.getSelectedValue().toString());
                jScrollPane4.setVisible(false);
                jList2.setVisible(false);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jList2MousePressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        try {
            txtSearch_Workout_for_Shed.setText("");
            jComboBox2.setSelectedIndex(0);
            jButton_add.setEnabled(false);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton_Update_workout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Update_workout1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Update_workout1ActionPerformed

    private void jButton_Update_workout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Update_workout2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Update_workout2ActionPerformed

    private void jButton_Update_workout3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Update_workout3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Update_workout3ActionPerformed

    private void txtSerach1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerach1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerach1KeyReleased

    private void txtSerach1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerach1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerach1KeyTyped

    private void jButton2_search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2_search1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2_search;
    private javax.swing.JButton jButton2_search1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton_Save_Shedule;
    private javax.swing.JButton jButton_Save_Workout;
    private javax.swing.JButton jButton_Update_workout;
    private javax.swing.JButton jButton_Update_workout1;
    private javax.swing.JButton jButton_Update_workout2;
    private javax.swing.JButton jButton_Update_workout3;
    private javax.swing.JButton jButton_add;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea txtDes;
    private javax.swing.JTextField txtSearch_Workout_for_Shed;
    private javax.swing.JTextField txtSerach;
    private javax.swing.JTextField txtSerach1;
    private javax.swing.JTextField txtSheduleName;
    private javax.swing.JTextField txtWname;
    // End of variables declaration//GEN-END:variables

    private void EmptyTF() {
        i = 0;
        txtWname.setText("");
        txtDes.setText("");

        jButton_Save_Workout.setEnabled(false);
        jButton_Update_workout.setEnabled(false);

    }

    private void TabelAdd() {

        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        Vector v = new Vector();

        v.add(txtWname.getText());
        v.add(txtDes.getText());

        dtm.addRow(v);

    }

    private void loadShed_to_Combo() {

        try {

            ResultSet rs = DB.search("SELECT Shedule From shedule_reg");
            DefaultComboBoxModel dcm = (DefaultComboBoxModel) jComboBox2.getModel();
            dcm.removeAllElements();
            dcm.addElement(" ");
            while (rs.next()) {

                dcm.addElement(rs.getString("Shedule"));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void Load_workouts(Object selectedItem) {

        try {
            byte Sid = 0;
            ResultSet rs = DB.search("SELECT Shed_Id FROM shedule_reg WHERE Shedule = '" + selectedItem.toString() + "' ");
            while (rs.next()) {
                Sid = Byte.parseByte(rs.getString("Shed_Id"));

            }

            ResultSet rs1 = Class_Files.DB.search("SELECT W_id FROM shedule_reg_has_workout WHERE Shed_Id = '" + Sid + "' ");
            DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
            dtm.setRowCount(0);
            while (rs1.next()) {

                ResultSet rs2 = DB.search("SELECT Workout FROM workout_reg WHERE W_id = '" + rs1.getInt("W_id") + "' ");
                while (rs2.next()) {
                    Vector v = new Vector();
                    v.add(rs2.getString("Workout"));
                    dtm.addRow(v);

                }

            }
        } catch (NullPointerException n) {
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
}
