/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logging_Forget_Pass;

import javax.swing.JOptionPane;

/**
 *
 * @author Buwaneka
 */
public class Forget_password extends javax.swing.JFrame {

    /**
     * Creates new form Forget_password
     */
    public Forget_password() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jComboBox2_Security_Q = new javax.swing.JComboBox();
        txtanswer = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton5_clear_all = new javax.swing.JButton();
        jButton5_clear_all1 = new javax.swing.JButton();
        txtverifycode = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtverifycode1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        jButton5_clear_all2 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(208, 171, 3));
        jPanel2.setLayout(null);

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Recovery Options");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(20, 20, 220, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("X");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9);
        jLabel9.setBounds(860, 0, 60, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 920, 70);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(570, 90, 10, 280);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(270, 90, 20, 280);

        jComboBox2_Security_Q.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jComboBox2_Security_Q.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "What is your favourite color?", "What is your favourite drink?", "What is your favourite Food?", "What is your Blood type?", "What is your favourite place to visit?" }));
        jComboBox2_Security_Q.setFocusable(false);
        jComboBox2_Security_Q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2_Security_QActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2_Security_Q);
        jComboBox2_Security_Q.setBounds(10, 150, 250, 30);

        txtanswer.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txtanswer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtanswerKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtanswerKeyTyped(evt);
            }
        });
        jPanel1.add(txtanswer);
        txtanswer.setBounds(10, 210, 250, 28);

        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Security Question :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 120, 120, 21);

        jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Answer :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 185, 140, 20);

        jButton5_clear_all.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jButton5_clear_all.setText("Submit");
        jButton5_clear_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5_clear_allActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5_clear_all);
        jButton5_clear_all.setBounds(120, 260, 140, 30);

        jButton5_clear_all1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jButton5_clear_all1.setText("Finish");
        jButton5_clear_all1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5_clear_all1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5_clear_all1);
        jButton5_clear_all1.setBounds(730, 330, 140, 30);

        txtverifycode.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txtverifycode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtverifycodeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtverifycodeKeyTyped(evt);
            }
        });
        jPanel1.add(txtverifycode);
        txtverifycode.setBounds(290, 150, 250, 28);

        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Recovery Code :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(300, 110, 140, 40);

        txtverifycode1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txtverifycode1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtverifycode1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtverifycode1KeyTyped(evt);
            }
        });
        jPanel1.add(txtverifycode1);
        txtverifycode1.setBounds(590, 140, 250, 28);

        jLabel12.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText(" Password :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(590, 190, 150, 20);

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(590, 210, 250, 30);

        jLabel13.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText(" User Name :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(590, 100, 150, 40);

        jPasswordField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jPasswordField2);
        jPasswordField2.setBounds(590, 280, 250, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Re enter Password :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(590, 250, 150, 20);

        jButton5_clear_all2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jButton5_clear_all2.setText("Verify");
        jButton5_clear_all2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5_clear_all2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5_clear_all2);
        jButton5_clear_all2.setBounds(400, 200, 140, 30);

        jCheckBox1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
        jCheckBox1.setText("Edit");
        jCheckBox1.setContentAreaFilled(false);
        jCheckBox1.setFocusable(false);
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(840, 140, 70, 27);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2_Security_QActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2_Security_QActionPerformed

        try {

         

        
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jComboBox2_Security_QActionPerformed

    private void txtanswerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtanswerKeyReleased

        try {

           

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtanswerKeyReleased

    private void txtanswerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtanswerKeyTyped

        try {
            System.gc();

           

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtanswerKeyTyped

    private void jButton5_clear_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5_clear_allActionPerformed

        try {


        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5_clear_allActionPerformed

    private void jButton5_clear_all1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5_clear_all1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5_clear_all1ActionPerformed

    private void txtverifycodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtverifycodeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtverifycodeKeyReleased

    private void txtverifycodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtverifycodeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtverifycodeKeyTyped

    private void txtverifycode1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtverifycode1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtverifycode1KeyReleased

    private void txtverifycode1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtverifycode1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtverifycode1KeyTyped

    private void jButton5_clear_all2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5_clear_all2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5_clear_all2ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked

        int sty = JOptionPane.showConfirmDialog(this, "Are you sure?", "Conform", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);

        if (sty == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forget_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forget_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forget_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forget_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forget_password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5_clear_all;
    private javax.swing.JButton jButton5_clear_all1;
    private javax.swing.JButton jButton5_clear_all2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox2_Security_Q;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtanswer;
    private javax.swing.JTextField txtverifycode;
    private javax.swing.JTextField txtverifycode1;
    // End of variables declaration//GEN-END:variables
}
