/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home_Pages;

import Admin.Add_Employee;
import Admin.Add_Members;
import Admin.Create_user_accounts;
import Admin.Expence;
import Admin.Fitness_Plan;
import Admin.Payments;
import Admin.Reports;
import java.awt.FlowLayout;

/**
 *
 * @author Buwaneka
 */
public class Admin_Home extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Home
     */
    public Admin_Home() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2_Menu = new javax.swing.JPanel();
        Icon_Trainers = new javax.swing.JLabel();
        Icon_Members = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Icon_Members1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        Icon_Members2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Icon_Members3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Icon_Members4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        Icon_Members5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        Icon_Members6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        Icon_Members7 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jPanel2_Top = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel3_Pannel_Set = new javax.swing.JPanel();
        jPanel2_Logo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jPanel2_Menu.setBackground(new java.awt.Color(235, 192, 29));
        jPanel2_Menu.setLayout(null);

        Icon_Trainers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gym/Icon_Add_Trainers.png"))); // NOI18N
        Icon_Trainers.setText(" Members");
        jPanel2_Menu.add(Icon_Trainers);
        Icon_Trainers.setBounds(20, 160, 50, 40);

        Icon_Members.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gym/Icon_Add_Members.png"))); // NOI18N
        Icon_Members.setText(" Members");
        jPanel2_Menu.add(Icon_Members);
        Icon_Members.setBounds(20, 110, 50, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 19)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText(" Members");
        jPanel2_Menu.add(jLabel2);
        jLabel2.setBounds(70, 110, 150, 40);

        jLabel14.setFont(new java.awt.Font("Segoe UI Semilight", 0, 19)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Home");
        jPanel2_Menu.add(jLabel14);
        jLabel14.setBounds(70, 60, 130, 40);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home_Pages/Normal.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusable(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Home_Pages/230401.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2_Menu.add(jButton1);
        jButton1.setBounds(10, 110, 230, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 19)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText(" Employees");
        jPanel2_Menu.add(jLabel3);
        jLabel3.setBounds(70, 160, 140, 40);

        jButton2.setIcon(new javax.swing.ImageIcon("E:\\Induwa projects\\GYM\\Button\\Normal.png")); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusable(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Home_Pages/230401.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2_Menu.add(jButton2);
        jButton2.setBounds(10, 160, 230, 40);

        Icon_Members1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home_Pages/Icon_Add_User_Accounts.png"))); // NOI18N
        jPanel2_Menu.add(Icon_Members1);
        Icon_Members1.setBounds(20, 210, 50, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 19)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("User Accounts");
        jPanel2_Menu.add(jLabel4);
        jLabel4.setBounds(70, 210, 120, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home_Pages/Normal.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusable(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Home_Pages/230401.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2_Menu.add(jButton3);
        jButton3.setBounds(10, 210, 230, 40);

        Icon_Members2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gym/Icon_Home.png"))); // NOI18N
        Icon_Members2.setText(" Members");
        jPanel2_Menu.add(Icon_Members2);
        Icon_Members2.setBounds(20, 60, 50, 40);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home_Pages/Normal.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusable(false);
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Home_Pages/230401.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2_Menu.add(jButton4);
        jButton4.setBounds(10, 60, 230, 40);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 19)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Fitness Plan");
        jPanel2_Menu.add(jLabel6);
        jLabel6.setBounds(70, 260, 120, 40);

        Icon_Members3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gym/Icon_Fitness_Plan.png"))); // NOI18N
        Icon_Members3.setText(" Members");
        jPanel2_Menu.add(Icon_Members3);
        Icon_Members3.setBounds(20, 260, 50, 40);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home_Pages/Normal.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusable(false);
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Home_Pages/230401.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2_Menu.add(jButton5);
        jButton5.setBounds(10, 260, 230, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 19)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Home");
        jPanel2_Menu.add(jLabel7);
        jLabel7.setBounds(70, 60, 160, 40);

        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 19)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Packages Registry");
        jPanel2_Menu.add(jLabel11);
        jLabel11.setBounds(70, 310, 160, 40);

        Icon_Members4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gym/icon_Packages.png"))); // NOI18N
        Icon_Members4.setText(" Members");
        jPanel2_Menu.add(Icon_Members4);
        Icon_Members4.setBounds(20, 310, 50, 40);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home_Pages/Normal.png"))); // NOI18N
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setFocusable(false);
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Home_Pages/230401.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2_Menu.add(jButton6);
        jButton6.setBounds(10, 310, 230, 40);

        Icon_Members5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gym/Payments.png"))); // NOI18N
        Icon_Members5.setText(" Members");
        jPanel2_Menu.add(Icon_Members5);
        Icon_Members5.setBounds(20, 360, 50, 40);

        jLabel12.setFont(new java.awt.Font("Segoe UI Semilight", 0, 19)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Cash Account");
        jPanel2_Menu.add(jLabel12);
        jLabel12.setBounds(70, 360, 150, 40);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home_Pages/Normal.png"))); // NOI18N
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setFocusable(false);
        jButton7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Home_Pages/230401.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2_Menu.add(jButton7);
        jButton7.setBounds(10, 360, 230, 40);

        Icon_Members6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gym/icon_Reports.png"))); // NOI18N
        Icon_Members6.setText(" Members");
        jPanel2_Menu.add(Icon_Members6);
        Icon_Members6.setBounds(20, 410, 50, 40);

        jLabel13.setFont(new java.awt.Font("Segoe UI Semilight", 0, 19)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Reports");
        jPanel2_Menu.add(jLabel13);
        jLabel13.setBounds(70, 410, 130, 40);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home_Pages/Normal.png"))); // NOI18N
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setFocusable(false);
        jButton8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Home_Pages/230401.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2_Menu.add(jButton8);
        jButton8.setBounds(10, 410, 230, 40);

        jLabel15.setFont(new java.awt.Font("Segoe UI Semilight", 0, 19)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Backup & Restore");
        jPanel2_Menu.add(jLabel15);
        jLabel15.setBounds(70, 460, 150, 40);

        Icon_Members7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gym/icon_Backup_&_restore.png"))); // NOI18N
        Icon_Members7.setText(" ");
        jPanel2_Menu.add(Icon_Members7);
        Icon_Members7.setBounds(20, 460, 50, 40);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home_Pages/Normal.png"))); // NOI18N
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setFocusable(false);
        jButton9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Home_Pages/230401.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2_Menu.add(jButton9);
        jButton9.setBounds(10, 460, 230, 40);

        jPanel1.add(jPanel2_Menu);
        jPanel2_Menu.setBounds(0, 150, 260, 550);

        jPanel2_Top.setBackground(new java.awt.Color(212, 187, 8));
        jPanel2_Top.setLayout(null);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Version 1.01");
        jPanel2_Top.add(jLabel5);
        jLabel5.setBounds(10, 70, 90, 30);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ARUNA FITNESS CENTER GYM MANAGEMENT SYSTEM");
        jPanel2_Top.add(jLabel9);
        jLabel9.setBounds(10, 10, 490, 40);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Developed by SANKALPA SOLUTIONS");
        jPanel2_Top.add(jLabel10);
        jLabel10.setBounds(10, 50, 300, 30);

        jPanel3.setBackground(new java.awt.Color(235, 192, 29));
        jPanel3.setLayout(null);
        jPanel2_Top.add(jPanel3);
        jPanel3.setBounds(0, 0, 1040, 50);

        jPanel1.add(jPanel2_Top);
        jPanel2_Top.setBounds(260, 0, 1040, 100);

        jPanel3_Pannel_Set.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3_Pannel_Set.setLayout(null);
        jPanel1.add(jPanel3_Pannel_Set);
        jPanel3_Pannel_Set.setBounds(260, 100, 1040, 600);

        jPanel2_Logo.setBackground(new java.awt.Color(208, 171, 3));
        jPanel2_Logo.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home_Pages/Logo_Aruna.png"))); // NOI18N
        jPanel2_Logo.add(jLabel1);
        jLabel1.setBounds(0, 10, 250, 100);

        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ARUNA FITNESS CENTER");
        jPanel2_Logo.add(jLabel8);
        jLabel8.setBounds(40, 110, 190, 40);

        jPanel1.add(jPanel2_Logo);
        jPanel2_Logo.setBounds(0, 0, 260, 150);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            jPanel3_Pannel_Set.removeAll();
            jPanel3_Pannel_Set.setLayout(new FlowLayout());
            Add_Members adm = new Add_Members();
            adm.setVisible(true);
            jPanel3_Pannel_Set.add(adm);
            jPanel3_Pannel_Set.updateUI();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            jPanel3_Pannel_Set.removeAll();
            jPanel3_Pannel_Set.setLayout(new FlowLayout());
            Add_Employee adEmp = new Add_Employee();
            adEmp.setVisible(true);
            jPanel3_Pannel_Set.add(adEmp);
            jPanel3_Pannel_Set.updateUI();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try {
            jPanel3_Pannel_Set.removeAll();
            jPanel3_Pannel_Set.setLayout(new FlowLayout());
            Create_user_accounts Uacc = new Create_user_accounts();
            Uacc.setVisible(true);
            jPanel3_Pannel_Set.add(Uacc);
            jPanel3_Pannel_Set.updateUI();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        try {
            jPanel3_Pannel_Set.removeAll();
            jPanel3_Pannel_Set.setLayout(new FlowLayout());
            Fitness_Plan Fitness = new Fitness_Plan();
            Fitness.setVisible(true);
            jPanel3_Pannel_Set.add(Fitness);
            jPanel3_Pannel_Set.updateUI();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        try {
            jPanel3_Pannel_Set.removeAll();
            jPanel3_Pannel_Set.setLayout(new FlowLayout());
            Payments p = new Payments();
            p.setVisible(true);
            jPanel3_Pannel_Set.add(p);
            jPanel3_Pannel_Set.updateUI();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        try {
            jPanel3_Pannel_Set.removeAll();
            jPanel3_Pannel_Set.setLayout(new FlowLayout());
            Expence e = new Expence();
            e.setVisible(true);
            jPanel3_Pannel_Set.add(e);
            jPanel3_Pannel_Set.updateUI();

        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        try {
            jPanel3_Pannel_Set.removeAll();
            jPanel3_Pannel_Set.setLayout(new FlowLayout());
            Reports r = new Reports();
            r.setVisible(true);
            jPanel3_Pannel_Set.add(r);
            jPanel3_Pannel_Set.updateUI();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try {

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icon_Members;
    private javax.swing.JLabel Icon_Members1;
    private javax.swing.JLabel Icon_Members2;
    private javax.swing.JLabel Icon_Members3;
    private javax.swing.JLabel Icon_Members4;
    private javax.swing.JLabel Icon_Members5;
    private javax.swing.JLabel Icon_Members6;
    private javax.swing.JLabel Icon_Members7;
    private javax.swing.JLabel Icon_Trainers;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2_Logo;
    private javax.swing.JPanel jPanel2_Menu;
    private javax.swing.JPanel jPanel2_Top;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel3_Pannel_Set;
    // End of variables declaration//GEN-END:variables
}
