/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Progress;

import Logging_Forget_Pass.Logging;
import java.awt.Window;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Buwaneka
 */
public class Splash extends javax.swing.JFrame {

    /**
     * Creates new form Splash
     */
    public Splash() {
        initComponents();
        setLocationRelativeTo(null);
        md_pub_setOpaque(this, false);
        md_loadingPage();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jp_progress = new Progress.Custom_Pannel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jp_progress.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 102, 0));
        jLabel1.setText("Please Wait System is Loading");

        javax.swing.GroupLayout jp_progressLayout = new javax.swing.GroupLayout(jp_progress);
        jp_progress.setLayout(jp_progressLayout);
        jp_progressLayout.setHorizontalGroup(
            jp_progressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_progressLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jp_progressLayout.setVerticalGroup(
            jp_progressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_progressLayout.createSequentialGroup()
                .addGap(0, 190, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jp_progress);
        jp_progress.setBounds(280, 180, 230, 220);

        jPanel2.setBackground(new java.awt.Color(235, 192, 29));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 500, 520, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(235, 192, 29));
        jLabel3.setText("Welcome");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 310, 160, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel4.setText("All Rights Receved to IC");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(360, 460, 150, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(235, 192, 29));
        jLabel5.setText("METRO FITNESS");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 355, 260, 40);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(235, 192, 29));
        jLabel6.setText("GYM MANAGEMENT SYSTEM V1.01");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 400, 280, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Progress/Cover.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 519, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private Progress.Custom_Pannel jp_progress;
    // End of variables declaration//GEN-END:variables

    public void md_loadingPage() {

        try {
            new Thread(() -> {
                try {
                    for (int i = 1; i <= 100; i++) {
                        jp_progress.pro_g(i);
                        jp_progress.repaint();

                        if (i >= 58) {
                            jLabel1.setText("Please Wait Connecting with Database");

                        }

                        if (i >= 90) {
                            jLabel1.setText("We Almost Done need just few Second");

                        }
                        
                        if (i >= 100) {
                            Logging login = new Logging();
                            Splash.this.dispose();
                            login.setVisible(true);

                        }
                        
                        try {
                            Thread.sleep(90);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(Splash.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                } catch (Exception e) {
                }
            }).start();
        } catch (Exception e) {
        }

    }
    
    void load_pro_bar() {
        try {

            new Thread(new Runnable() {

                @Override
                public void run() {
                    for (int i = 1; i <= 100; i++) {
                        jp_progress.pro_g(i);
                        jp_progress.repaint();

                        if (i >= 58) {
                            jLabel1.setText("Please Wait Connecting with Database");

                        }

                        if (i >= 90) {
                            jLabel1.setText("We Almost Done need just few Second");

                        }

                        try {
                            Thread.sleep(90);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(Splash.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    pro.Exite();
                    //System.exit(0);

                }
            }).start();
            

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public static void md_pub_setOpaque(Window window, boolean opaque) {

        try {

            Class<?> awtUtilsClass = Class.forName("com.sun.awt.AWTUtilities");
            if (awtUtilsClass != null) {

                Method method = awtUtilsClass.getMethod("setWindowOpaque", Window.class, boolean.class);
                method.invoke(null, window, opaque);

            }

        } catch (ClassNotFoundException | IllegalAccessException | IllegalArgumentException | NoSuchMethodException | SecurityException | InvocationTargetException exp) {
            exp.printStackTrace();
        }

    }

}
