/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin.Employe_Sub;

import static Admin.Add_Employee.copyFile;
import Admin.add_members.Rc_1;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import static java.awt.image.ImageObserver.ERROR;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.channels.FileChannel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Buwaneka
 */
public class Add_Employee extends javax.swing.JPanel {

    Image img;
    String path = "";
    String Nic;
    String gen;
    int i;
    String newpath;
    File F;
    File F2;
    String pa;

    String Fname;
    String Lname;

    /**
     * Creates new form Add_Employee
     */
    public Add_Employee() {
        initComponents();
        jScrollPane3.setVisible(false);
        jList1.setVisible(false);
        jButton2_search.setEnabled(false);
        jButton5_Save.setEnabled(false);
        jButton4_Update.setEnabled(false);
        jRadioButton1.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        txtNic = new javax.swing.JTextField();
        jButton5_Save = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton4_Update = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        Image_Label = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtLname = new javax.swing.JTextField();
        txtFname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        txt_search = new javax.swing.JTextField();
        jButton2_search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Nic :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 90, 120, 21);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Image :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(360, 60, 120, 21);

        jTable1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Nic", "Gender", "Address", "Mobile", "Email", "Employee Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 320, 1000, 140);

        jComboBox2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Trainer", "Other" }));
        jComboBox2.setFocusable(false);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(480, 10, 200, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Address :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 170, 100, 21);

        jLabel9.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Employee Type :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(360, 10, 120, 30);

        jList1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jList1MousePressed(evt);
            }
        });
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jList1KeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jList1);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(750, 118, 220, 90);

        txtNic.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txtNic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNicKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNicKeyTyped(evt);
            }
        });
        jPanel1.add(txtNic);
        txtNic.setBounds(110, 90, 200, 28);

        jButton5_Save.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jButton5_Save.setText("Save");
        jButton5_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5_SaveActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5_Save);
        jButton5_Save.setBounds(750, 280, 130, 30);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jRadioButton1.setText("Male");
        jRadioButton1.setContentAreaFilled(false);
        jRadioButton1.setFocusable(false);
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(110, 130, 80, 29);

        jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Mobile :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 250, 120, 30);

        jLabel13.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel13.setText(" Name :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(690, 90, 70, 21);

        jButton6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jButton6.setText("Veiw All");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(750, 480, 130, 30);

        jButton4_Update.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jButton4_Update.setText("Update");
        jButton4_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4_Update);
        jButton4_Update.setBounds(890, 280, 120, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Last Name :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 55, 120, 21);

        jButton3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jButton3.setText("Clear All");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(890, 480, 120, 30);

        Image_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Image_Chose_Label.png"))); // NOI18N
        Image_Label.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jPanel1.add(Image_Label);
        Image_Label.setBounds(480, 50, 160, 170);

        txtContact.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txtContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContactKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContactKeyTyped(evt);
            }
        });
        jPanel1.add(txtContact);
        txtContact.setBounds(110, 250, 230, 28);

        txtEmail.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        jPanel1.add(txtEmail);
        txtEmail.setBounds(110, 285, 230, 28);

        txtLname.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txtLname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLnameKeyTyped(evt);
            }
        });
        jPanel1.add(txtLname);
        txtLname.setBounds(110, 55, 230, 28);

        txtFname.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txtFname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFnameKeyTyped(evt);
            }
        });
        jPanel1.add(txtFname);
        txtFname.setBounds(110, 20, 230, 28);

        jLabel14.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("First Name :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(20, 20, 120, 21);

        jButton1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(570, 230, 80, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Gender :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 130, 100, 21);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jRadioButton2.setText("Female");
        jRadioButton2.setContentAreaFilled(false);
        jRadioButton2.setFocusable(false);
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(200, 130, 100, 29);

        txt_search.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_searchKeyTyped(evt);
            }
        });
        jPanel1.add(txt_search);
        txt_search.setBounds(750, 90, 220, 28);

        jButton2_search.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jButton2_search.setText("Search");
        jButton2_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_searchActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2_search);
        jButton2_search.setBounds(880, 150, 110, 30);

        txtAddress.setColumns(20);
        txtAddress.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        txtAddress.setRows(5);
        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAddressKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txtAddress);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(110, 160, 290, 80);

        jComboBox1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "x", "v" }));
        jComboBox1.setFocusable(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(310, 90, 40, 28);

        jLabel15.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Email :");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(20, 290, 120, 21);

        jLabel12.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 0, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(680, 50, 320, 170);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jList1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MousePressed

        try {
            System.gc();
            if (evt.getClickCount() == 2) {
                txt_search.setText(jList1.getSelectedValue().toString());
                jScrollPane3.setVisible(false);
                jList1.setVisible(false);

            }
            ////////////////////////////////////////
            //            if (txtSearchname.getText().length() == 0) {
            //                serach_Button.setEnabled(false);
            //
            //            } else {
            //                if (txtSearchEid.getText().length() != 0 || txtSearchname.getText().length() != 0) {
            //                    serach_Button.setEnabled(true);
            //
            //                }
            //
            //            }

        } catch (NullPointerException n) {
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jList1MousePressed

    private void jList1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyReleased

        try {
            System.gc();
            if (evt.getKeyCode() == 10) {
                txt_search.setText(jList1.getSelectedValue().toString());
                jScrollPane3.setVisible(false);
                jList1.setVisible(false);
                jButton2_search.grabFocus();

            }
        } catch (NullPointerException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jList1KeyReleased

    private void txtFnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFnameKeyReleased

        try {

            String EMAIL_REGEX = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";

            Boolean b = txtEmail.getText().matches(EMAIL_REGEX);

            if (txtFname.getText().length() == 0) {
                jButton5_Save.setEnabled(false);
                jButton4_Update.setEnabled(false);
            } else {

                if (txtFname.getText().length() != 0
                        && txtLname.getText().length() != 0
                        && txtNic.getText().length() != 0
                        && jComboBox1.getSelectedIndex() != 0
                        && txtAddress.getText().length() != 0
                        && txtContact.getText().length() != 0
                        && txtEmail.getText().length() != 0
                        && jComboBox2.getSelectedIndex() != 0
                        && !path.equals("") && b) {

                    jButton5_Save.setEnabled(true);
                    jButton4_Update.setEnabled(true);

                } else {
                    jButton5_Save.setEnabled(false);
                    jButton4_Update.setEnabled(false);
                }

            }

            /////////////////////////////////////////
            if (i == 10) {
                jButton5_Save.setEnabled(false);
            } else {
                jButton4_Update.setEnabled(false);
            }

            ///Grab Focus
            if (evt.getKeyCode() == 10) {

                txtLname.grabFocus();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtFnameKeyReleased

    private void txtFnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFnameKeyTyped

        try {
            System.gc();

            char c = evt.getKeyChar();
            if (Character.isDigit(c) || c == 32) {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtFnameKeyTyped

    private void jButton2_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_searchActionPerformed

        try {
            if (!txt_search.getText().equals("")) {

                byte d = 0;

                String Name[] = txt_search.getText().split(" ");
                DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                dtm.setRowCount(0);
                Vector v = new Vector();
                ResultSet rs = Class_Files.DB.search("SELECT * FROM employee_reg WHERE First_Name = '" + Name[0] + "' && Last_Name='" + Name[1] + "' ");
                while (rs.next()) {
                    d = 1;
                    v.add(rs.getString("First_Name"));
                    v.add(rs.getString("Last_Name"));
                    v.add(rs.getString("Nic"));
                    v.add(rs.getString("Gender"));
                    v.add(rs.getString("Address"));
                    v.add(rs.getString("Contact"));
                    v.add(rs.getString("Email"));
                    v.add(rs.getString("Emp_Type"));

                    dtm.addRow(v);
                }

                if (d == 0) {
                    JOptionPane.showMessageDialog(this, "Sorry No result found..!");
                }

                txt_search.setText("");
                jButton2_search.setEnabled(false);
                EmtyTF();
                txtFname.grabFocus();

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton2_searchActionPerformed

    private void txtLnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLnameKeyReleased

        try {
            String EMAIL_REGEX = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";

            Boolean b = txtEmail.getText().matches(EMAIL_REGEX);

            if (txtLname.getText().length() == 0) {
                jButton5_Save.setEnabled(false);
                jButton4_Update.setEnabled(false);
            } else {

                if (txtFname.getText().length() != 0
                        && txtLname.getText().length() != 0
                        && txtNic.getText().length() != 0
                        && jComboBox1.getSelectedIndex() != 0
                        && txtAddress.getText().length() != 0
                        && txtContact.getText().length() != 0
                        && txtEmail.getText().length() != 0
                        && jComboBox2.getSelectedIndex() != 0
                        && !path.equals("") && b) {

                    jButton5_Save.setEnabled(true);
                    jButton4_Update.setEnabled(true);

                } else {
                    jButton5_Save.setEnabled(false);
                    jButton4_Update.setEnabled(false);
                }

            }

            /////////////////////////////////////////
            if (i == 10) {
                jButton5_Save.setEnabled(false);
            } else {
                jButton4_Update.setEnabled(false);
            }

            ///Grab Focus
            if (evt.getKeyCode() == 10) {

                txtNic.grabFocus();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtLnameKeyReleased

    private void txtLnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLnameKeyTyped

        try {
            System.gc();

            char c = evt.getKeyChar();
            if (Character.isDigit(c) || c == 32) {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtLnameKeyTyped

    private void txtNicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNicKeyReleased

        try {

            String EMAIL_REGEX = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";

            Boolean b = txtEmail.getText().matches(EMAIL_REGEX);

            if (txtNic.getText().length() == 0) {
                jButton5_Save.setEnabled(false);
                jButton4_Update.setEnabled(false);
            } else {

                if (txtFname.getText().length() != 0
                        && txtLname.getText().length() != 0
                        && txtNic.getText().length() != 0
                        && jComboBox1.getSelectedIndex() != 0
                        && txtAddress.getText().length() != 0
                        && txtContact.getText().length() != 0
                        && txtEmail.getText().length() != 0
                        && jComboBox2.getSelectedIndex() != 0
                        && !path.equals("") && b) {

                    jButton5_Save.setEnabled(true);
                    jButton4_Update.setEnabled(true);

                } else {
                    jButton5_Save.setEnabled(false);
                    jButton4_Update.setEnabled(false);
                }

            }

            /////////////////////////////////////////
            if (i == 10) {
                jButton5_Save.setEnabled(false);
            } else {
                jButton4_Update.setEnabled(false);
            }
            //////////////////////////////////////////

            ///Grab Focus
            if (evt.getKeyCode() == 10) {

                jComboBox1.grabFocus();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtNicKeyReleased

    private void txtNicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNicKeyTyped

        try {
            char c = evt.getKeyChar();
            int a = txtNic.getText().length();

            if (!Character.isDigit(c) || a > 8) {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtNicKeyTyped

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        try {
            String EMAIL_REGEX = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";

            Boolean b = txtEmail.getText().matches(EMAIL_REGEX);

            if (jComboBox1.getSelectedIndex() == 0) {
                jButton5_Save.setEnabled(false);
                jButton4_Update.setEnabled(false);
            } else {

                if (txtFname.getText().length() != 0
                        && txtLname.getText().length() != 0
                        && txtNic.getText().length() != 0
                        && jComboBox1.getSelectedIndex() != 0
                        && txtAddress.getText().length() != 0
                        && txtContact.getText().length() != 0
                        && txtEmail.getText().length() != 0
                        && jComboBox2.getSelectedIndex() != 0
                        && !path.equals("") && b) {

                    jButton5_Save.setEnabled(true);
                    jButton4_Update.setEnabled(true);

                } else {
                    jButton5_Save.setEnabled(false);
                    jButton4_Update.setEnabled(false);
                }

            }

            /////////////////////////////////////////
            if (i == 10) {
                jButton5_Save.setEnabled(false);
            } else {
                jButton4_Update.setEnabled(false);
            }
            //////////////////////////////////////////

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyReleased

        try {

            String EMAIL_REGEX = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";

            Boolean b = txtEmail.getText().matches(EMAIL_REGEX);

            if (txtAddress.getText().length() == 0) {
                jButton5_Save.setEnabled(false);
                jButton4_Update.setEnabled(false);
            } else {

                if (txtFname.getText().length() != 0
                        && txtLname.getText().length() != 0
                        && txtNic.getText().length() != 0
                        && jComboBox1.getSelectedIndex() != 0
                        && txtAddress.getText().length() != 0
                        && txtContact.getText().length() != 0
                        && txtEmail.getText().length() != 0
                        && jComboBox2.getSelectedIndex() != 0
                        && !path.equals("") && b) {

                    jButton5_Save.setEnabled(true);
                    jButton4_Update.setEnabled(true);

                } else {
                    jButton5_Save.setEnabled(false);
                    jButton4_Update.setEnabled(false);
                }

            }

            /////////////////////////////////////////
            if (i == 10) {
                jButton5_Save.setEnabled(false);
            } else {
                jButton4_Update.setEnabled(false);
            }
            //////////////////////////////////////////

            ///Grab Focus
            if (evt.getKeyCode() == 10) {

                txtContact.grabFocus();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtAddressKeyReleased

    private void txtContactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactKeyReleased

        try {

            String EMAIL_REGEX = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";

            Boolean b = txtEmail.getText().matches(EMAIL_REGEX);

            if (txtContact.getText().length() == 0) {
                jButton5_Save.setEnabled(false);
                jButton4_Update.setEnabled(false);
            } else {

                if (txtFname.getText().length() != 0
                        && txtLname.getText().length() != 0
                        && txtNic.getText().length() != 0
                        && jComboBox1.getSelectedIndex() != 0
                        && txtAddress.getText().length() != 0
                        && txtContact.getText().length() != 0
                        && txtEmail.getText().length() != 0
                        && jComboBox2.getSelectedIndex() != 0
                        && !path.equals("") && b) {

                    jButton5_Save.setEnabled(true);
                    jButton4_Update.setEnabled(true);

                } else {
                    jButton5_Save.setEnabled(false);
                    jButton4_Update.setEnabled(false);
                }

            }

            /////////////////////////////////////////
            if (i == 10) {
                jButton5_Save.setEnabled(false);
            } else {
                jButton4_Update.setEnabled(false);
            }
            //////////////////////////////////////////

            ///Grab Focus
            if (evt.getKeyCode() == 10) {

                txtEmail.grabFocus();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtContactKeyReleased

    private void txtContactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactKeyTyped

        try {
            System.gc();
            int a = txtContact.getText().length();
            char c = evt.getKeyChar();

            if (!Character.isDigit(c) || a >= 10) {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtContactKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            Image_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Image_Chose_Label.png")));
            System.gc();
            Class_Files.ImageSelect is = new Class_Files.ImageSelect();

            BufferedImage image = is.showDialog();

            path = is.getPath();
//////////////////////////////////////////////////////////////////////////////////
            newpath = path.replace("\\", "//");
            F = new File(newpath);
            String s = System.currentTimeMillis() + "";

            F2 = new File("C:\\Users\\Buwaneka\\Documents\\NetBeansProjects\\PROJECT_Gym\\Browsed_Images\\Employee\\" + s + ".jpg");
            copyFile(F, F2);

            String pat = F2.getAbsolutePath();
            pa = pat.replace("\\", "//");

            ///////////////////////////////////////////////////////////////////////////////          
            File f1 = new File(pa);
            Image img = ImageIO.read(f1);

            img = img.getScaledInstance(Image_Label.getWidth(), Image_Label.getHeight(), java.awt.Image.SCALE_SMOOTH);

            Image_Label.setIcon(new ImageIcon(img));

            //////Validation
            String EMAIL_REGEX = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";

            Boolean b = txtEmail.getText().matches(EMAIL_REGEX);
            if (path.equals("")) {
                jButton5_Save.setEnabled(false);
                jButton4_Update.setEnabled(false);
            } else {

                if (txtFname.getText().length() != 0
                        && txtLname.getText().length() != 0
                        && txtNic.getText().length() != 0
                        && jComboBox1.getSelectedIndex() != 0
                        && txtAddress.getText().length() != 0
                        && txtContact.getText().length() != 0
                        && txtEmail.getText().length() != 0
                        && jComboBox2.getSelectedIndex() != 0
                        && !path.equals("") && b) {

                    jButton5_Save.setEnabled(true);
                    jButton4_Update.setEnabled(true);

                } else {
                    jButton5_Save.setEnabled(false);
                    jButton4_Update.setEnabled(false);
                }

            }
/////////////////////////////////////////////////////////

            /////////////////////////////////////////
            if (i == 10) {
                jButton5_Save.setEnabled(false);
            } else {
                jButton4_Update.setEnabled(false);
            }
            //////////////////////////////////////////

        } catch (NullPointerException n) {
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5_SaveActionPerformed

        try {
            if (jRadioButton1.isSelected()) {
                gen = "Male";

            } else {
                gen = "Female";
            }
            /////////////////////////////////////////////////////////////////////////
            Nic = txtNic.getText() + " " + jComboBox1.getSelectedItem();

            Class_Files.DB.sud("INSERT INTO employee_reg(First_Name,Last_Name,Nic,Gender,Address,Contact,Email,Emp_Type,Image,Status)VALUES('" + txtFname.getText() + "'"
                    + ",'" + txtLname.getText() + "'"
                    + ",'" + Nic + "'"
                    + ",'" + gen + "'"
                    + ",'" + txtAddress.getText() + "'"
                    + ",'" + txtContact.getText() + "'"
                    + ", '" + txtEmail.getText() + "' "
                    + ", '" + jComboBox2.getSelectedItem() + "'"
                    + ", '" + pa + "'"
                    + ",'" + "On" + "')");

            JOptionPane.showMessageDialog(this, "Save Sucess");

            tabelAdd();
            EmtyTF();
            path = "";

            //////////////////////////////////////////////////////////*************
        } catch (SQLException u) {
            if (u.toString().equals("java.sql.SQLException: Result of load_file() was larger than max_allowed_packet (1048576) - truncated")) {
                JOptionPane.showMessageDialog(this, "Sorry Image is too large", "Inform", ERROR);
            }
            u.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton5_SaveActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased

        try {

            if (!txt_search.getText().trim().equals("")) {
                ResultSet rs = Class_Files.DB.search("SELECT * FROM employee_reg WHERE First_Name LIKE '" + txt_search.getText() + "%' || Last_Name LIKE '" + txt_search.getText() + "%' ");
                Vector v = new Vector();
                jList1.removeAll();

                while (rs.next()) {

                    String sts = rs.getString("Status");

                    if (sts.equals("On")) {

                        jScrollPane3.setVisible(true);
                        jList1.setVisible(true);
                        jButton2_search.setEnabled(true);

                        String Fn = rs.getString("First_Name");
                        String Ln = rs.getString("Last_Name");
                        v.add(Fn + " " + Ln);
                        jList1.setListData(v);

                    }

                }

            } else {
                jScrollPane3.setVisible(false);
                jList1.setVisible(false);
                jButton2_search.setEnabled(false);

            }

            /////////////////////////////////////////////////////////
            if (jList1.isVisible()) {
                if (evt.getKeyCode() == 40) {
                    jList1.grabFocus();
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txt_searchKeyReleased

    private void txt_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyTyped
        try {
            char c = evt.getKeyChar();
            if (Character.isDigit(c)) {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txt_searchKeyTyped
    int eid = 0;
    private void jButton4_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_UpdateActionPerformed

        try {
            //Load Employee ID For Update Where Close

            ResultSet rs = Class_Files.DB.search("SELECT E_Id FROM employee_reg WHERE First_Name='" + Fname + "' && Last_Name='" + Lname + "' ");
            while (rs.next()) {
                eid = Integer.parseInt(rs.getString("E_Id"));
            }
//////////////////////////////////////////////////////////////////////////////
            if (jRadioButton1.isSelected()) {
                gen = "Male";

            } else {
                gen = "Female";
            }
/////////////////////////////////////////////////////////////////////////
            Nic = txtNic.getText() + " " + jComboBox1.getSelectedItem();

            if (!path.equals(" ")) {

                Class_Files.DB.sud(" UPDATE employee_reg SET First_Name = '" + txtFname.getText() + "' "
                        + ", Last_Name= '" + txtLname.getText() + "' "
                        + ", Nic = '" + Nic + "'"
                        + ", Gender = '" + gen + "' "
                        + ", Address = '" + txtAddress.getText() + "' "
                        + ", Contact = '" + txtContact.getText() + "' "
                        + ", Email = '" + txtEmail.getText() + "' "
                        + " , Emp_Type = '" + jComboBox2.getSelectedItem() + "'"
                        + " ,Image = '" + pa + "'  WHERE E_id = '" + eid + "' ");

            } else {

                Class_Files.DB.sud(" UPDATE employee_reg SET First_Name = '" + txtFname.getText() + "' "
                        + ", Last_Name= '" + txtLname.getText() + "' "
                        + ", Nic = '" + Nic + "'"
                        + ", Gender = '" + gen + "' "
                        + ", Address = '" + txtAddress.getText() + "' "
                        + ", Contact = '" + txtContact.getText() + "' "
                        + ", Email = '" + txtEmail.getText() + "' "
                        + " , Emp_Type = '" + jComboBox2.getSelectedItem() + "'  WHERE E_id = '" + eid + "' ");

            }

            path = "";
            i = 0;
            tabelAdd();
            EmtyTF();

            JOptionPane.showMessageDialog(this, "Update Success..!");

        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton4_UpdateActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed

        try {
            System.gc();

            if (evt.getButton() == 1) {

                if (evt.getClickCount() == 2) {

                    i = 10;
                    int row = jTable1.getSelectedRow();
                    path = " ";

                    Fname = jTable1.getValueAt(row, 0).toString();
                    Lname = jTable1.getValueAt(row, 1).toString();
                    String Nic[] = jTable1.getValueAt(row, 2).toString().split(" ");
                    String Gen = jTable1.getValueAt(row, 3).toString();
                    String Add = jTable1.getValueAt(row, 4).toString();
                    String Cont = jTable1.getValueAt(row, 5).toString();
                    String Email = jTable1.getValueAt(row, 6).toString();
                    String Etype = jTable1.getValueAt(row, 7).toString();

                    txtFname.setText(Fname);
                    txtLname.setText(Lname);
                    txtNic.setText(Nic[0]);
                    jComboBox1.setSelectedItem(Nic[1]);

                    if (Gen.equals("Male")) {
                        jRadioButton1.setSelected(true);
                    } else {
                        jRadioButton2.setSelected(true);
                    }

                    txtAddress.setText(Add);
                    txtContact.setText(Cont);
                    txtEmail.setText(Email);
                    jComboBox2.setSelectedItem(Etype);

                    ResultSet rs = Class_Files.DB.search("SELECT * FROM employee_reg WHERE First_Name = '" + Fname + "' && Last_Name='" + Lname + "' ");
                    while (rs.next()) {
                        String imagedata = rs.getString("Image");
                        File f = new File(imagedata);
                        Image img = ImageIO.read(f);
                        img = img.getScaledInstance(Image_Label.getWidth(), Image_Label.getHeight(), java.awt.Image.SCALE_SMOOTH);
                        Image_Label.setIcon(new ImageIcon(img));

                    }

                    jButton4_Update.setEnabled(true);

                } else {

                    int ro = jTable1.getSelectedRow();
                    Fname = jTable1.getValueAt(ro, 0).toString();
                    Lname = jTable1.getValueAt(ro, 1).toString();

                    ResultSet rs2 = Class_Files.DB.search("SELECT * FROM employee_reg WHERE First_Name = '" + Fname + "' && Last_Name='" + Lname + "' ");
                    while (rs2.next()) {
                        eid = rs2.getInt("E_Id");
                    }

                }

            }

            ///If Right Click   
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();

            if (jTable1.isRowSelected(jTable1.getSelectedRow())) {

                Rc_2 rc2 = null;

                if (evt.getButton() == 3) {
                    rc2 = new Rc_2(x, y, new javax.swing.JFrame(), true);
                    rc2.Eid = eid;
                    rc2.setVisible(true);
                } else {
                    rc2 = new Rc_2(x, y, new javax.swing.JFrame(), true);
                    rc2.dispose();

                }
            } else {

                Rc_1 rc = new Rc_1(x, y, new javax.swing.JFrame(), true);
                rc.setVisible(false);
                rc.dispose();
            }

        } catch (NullPointerException n) {

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTable1MousePressed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed

        try {

            String EMAIL_REGEX = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";

            Boolean b = txtEmail.getText().matches(EMAIL_REGEX);

            if (jComboBox2.getSelectedIndex() == 0) {
                jButton5_Save.setEnabled(false);
                jButton4_Update.setEnabled(false);
            } else {

                if (txtFname.getText().length() != 0
                        && txtLname.getText().length() != 0
                        && txtNic.getText().length() != 0
                        && jComboBox1.getSelectedIndex() != 0
                        && txtAddress.getText().length() != 0
                        && txtContact.getText().length() != 0
                        && txtEmail.getText().length() != 0
                        && jComboBox2.getSelectedIndex() != 0
                        && !path.equals("") && b) {

                    jButton5_Save.setEnabled(true);
                    jButton4_Update.setEnabled(true);

                } else {
                    jButton5_Save.setEnabled(false);
                    jButton4_Update.setEnabled(false);
                }

            }

            /////////////////////////////////////////
            if (i == 10) {
                jButton5_Save.setEnabled(false);
            } else {
                jButton4_Update.setEnabled(false);
            }
            //////////////////////////////////////////

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased

        try {

            String EMAIL_REGEX = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";

            Boolean b = txtEmail.getText().matches(EMAIL_REGEX);

            if (!b) {
                jButton5_Save.setEnabled(false);
                jButton4_Update.setEnabled(false);
            } else {

                if (txtFname.getText().length() != 0
                        && txtLname.getText().length() != 0
                        && txtNic.getText().length() != 0
                        && jComboBox1.getSelectedIndex() != 0
                        && txtAddress.getText().length() != 0
                        && txtContact.getText().length() != 0
                        && b
                        && jComboBox2.getSelectedIndex() != 0
                        && !path.equals("")) {

                    jButton5_Save.setEnabled(true);
                    jButton4_Update.setEnabled(true);

                } else {
                    jButton5_Save.setEnabled(false);
                    jButton4_Update.setEnabled(false);
                }

            }

            /////////////////////////////////////////
            if (i == 10) {
                jButton5_Save.setEnabled(false);
            } else {
                jButton4_Update.setEnabled(false);
            }
            //////////////////////////////////////////

            ///Grab Focus
            if (evt.getKeyCode() == 10) {

                jComboBox2.grabFocus();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_txtEmailKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try {
            System.gc();
            EmtyTF();
            txt_search.setText("");
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            path = "";
            i = 0;
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        try {

            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);

            ResultSet rs = Class_Files.DB.search("SELECT * FROM employee_reg");

            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString("First_Name"));
                v.add(rs.getString("Last_Name"));
                v.add(rs.getString("Nic"));
                v.add(rs.getString("Gender"));
                v.add(rs.getString("Address"));
                v.add(rs.getString("Contact"));
                v.add(rs.getString("Email"));
                v.add(rs.getString("Emp_Type"));

                dtm.addRow(v);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Image_Label;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2_search;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4_Update;
    private javax.swing.JButton jButton5_Save;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtNic;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables

    public static void copyFile(File sourceFile, File destFile) throws IOException {

        if (!destFile.exists()) {
            destFile.createNewFile();
        }
        FileInputStream fIn = null;
        FileOutputStream fOut = null;
        FileChannel source = null;
        FileChannel destination = null;
        try {
            fIn = new FileInputStream(sourceFile);
            source = fIn.getChannel();
            fOut = new FileOutputStream(destFile);
            destination = fOut.getChannel();
            long transfered = 0;
            long bytes = source.size();
            while (transfered < bytes) {
                transfered += destination.transferFrom(source, 0, source.size());
                destination.position(transfered);
            }
        } finally {
            if (source != null) {
                source.close();
            } else if (fIn != null) {
                fIn.close();
            }
            if (destination != null) {
                destination.close();
            } else if (fOut != null) {
                fOut.close();
            }
        }

    }

    public void EmtyTF() throws Exception {
        txtFname.setText("");
        txtLname.setText("");
        txtNic.setText("");
        jComboBox1.setSelectedIndex(0);
        jRadioButton1.setSelected(true);
        txtAddress.setText("");
        txtContact.setText("");
        txtEmail.setText("");
        jComboBox2.setSelectedIndex(0);
        Image_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Image_Chose_Label.png")));
        jButton5_Save.setEnabled(false);
        jButton4_Update.setEnabled(false);

    }

    private void tabelAdd() throws Exception {

        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        Vector v = new Vector();
        v.add(txtFname.getText());
        v.add(txtLname.getText());
        v.add(Nic);
        v.add(gen);
        v.add(txtAddress.getText());
        v.add(txtContact.getText());
        v.add(txtEmail.getText());
        v.add(jComboBox2.getSelectedItem());

        dtm.addRow(v);

    }

}
