/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin.Employe_Sub;

import Class_Files.DB;
import java.awt.Image;
import java.io.File;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Buwaneka
 */
public class View_employee_details extends javax.swing.JDialog {

    /**
     * Creates new form View_employee_details
     */
    public View_employee_details(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Image_Label = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEtype = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txtMobile = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtGen = new javax.swing.JTextField();
        txtNic = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Employee Details");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 20, 150, 30);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(null);

        jButton1.setText("x");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(833, 10, 50, 23);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 900, 70);

        Image_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Image_Chose_Label.png"))); // NOI18N
        Image_Label.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jPanel1.add(Image_Label);
        Image_Label.setBounds(30, 90, 160, 170);

        txtemail.setEditable(false);
        txtemail.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jPanel1.add(txtemail);
        txtemail.setBounds(655, 150, 220, 28);

        jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Mobile :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(540, 110, 100, 21);

        txtEtype.setEditable(false);
        txtEtype.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jPanel1.add(txtEtype);
        txtEtype.setBounds(655, 190, 220, 28);

        jLabel9.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Name :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(210, 110, 130, 21);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Email :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(540, 150, 120, 21);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(280, 230, 230, 90);

        txtMobile.setEditable(false);
        txtMobile.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jPanel1.add(txtMobile);
        txtMobile.setBounds(655, 110, 220, 28);

        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Gender :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(210, 190, 100, 21);

        txtGen.setEditable(false);
        txtGen.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jPanel1.add(txtGen);
        txtGen.setBounds(280, 190, 230, 28);

        txtNic.setEditable(false);
        txtNic.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jPanel1.add(txtNic);
        txtNic.setBounds(280, 150, 230, 28);

        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Employee type :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(540, 190, 150, 30);

        txtFname.setEditable(false);
        txtFname.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jPanel1.add(txtFname);
        txtFname.setBounds(280, 110, 230, 28);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Address :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(210, 230, 100, 21);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Nic :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(210, 150, 130, 21);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 897, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            this.dispose();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_employee_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_employee_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_employee_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_employee_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                View_employee_details dialog = new View_employee_details(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Image_Label;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtEtype;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtGen;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtNic;
    private javax.swing.JTextField txtemail;
    // End of variables declaration//GEN-END:variables

    String imagedata;
    Image img;

    public void load_Employee_data(int id) {

        try {

            ResultSet rs = DB.search("SELECT * FROM employee_reg WHERE E_Id= '" + id + "' ");
            while (rs.next()) {
                txtFname.setText(rs.getString("First_Name") + " " + rs.getString("Last_Name"));
                txtNic.setText(rs.getString("Nic"));
                txtGen.setText(rs.getString("Gender"));
                jTextArea1.setText(rs.getString("Address"));
                txtMobile.setText(rs.getString("Contact"));
                txtemail.setText(rs.getString("Email"));
                txtEtype.setText(rs.getString("Emp_Type"));

                imagedata = rs.getString("Image");
                File f = new File(imagedata);
                Image img = ImageIO.read(f);

                img = img.getScaledInstance(Image_Label.getWidth(), Image_Label.getHeight(), java.awt.Image.SCALE_SMOOTH);
                Image_Label.setIcon(new ImageIcon(img));

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

}
